# Infleeting Lead Times — Compound Deep Dive

Analyzes actual days per infleeting phase (ordered → produced → arrived → tech prep → ready → in_subscription) by brand and compound.

**Data source**: `datawarehouse-304513.cars_ops_postgres_public.car_events`  
**API source**: `https://api-ops-cars.finn.auto` (ops-cars API, documented in `finn-auto/redocly`)

In [1]:
from google.cloud import bigquery
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

client = bigquery.Client(project='datawarehouse-304513')

def run_query(sql):
    return client.query(sql).to_dataframe()

## 1. Brand / Compound Configuration

Current compound assignments from the ops-cars lead times config:

In [2]:
COMPOUND_MAP = [
    ('Mazda', 'cat_zuelpich'), ('Ford', 'cat_zuelpich'), ('Polestar', 'cat_zuelpich'),
    ('Honda', 'akb_kitzingen'), ('Kia', 'blg_bremerhaven'), ('Kia', 'blg_saalanderdonau'),
    ('Nissan', 'blg_neuss'), ('Mazda', 'blg_duisburg'),
    ('Cadillac', 'ceva_grevenbroich'), ('Cadillac', 'ceva_bad_salzungen'),
    ('Hyundai', 'blg_bremerhaven'), ('Hyundai', 'mosolf_rackwitz'), ('Hyundai', 'mosolf_cuxhaven'),
    ('Jeep', 'mosolf_goessnitz'), ('Jeep', 'mosolf_kippenheim'), ('Jeep', 'mosolf_etzin'),
    ('Fiat', 'mosolf_kippenheim'), ('Fiat', 'mosolf_etzin'),
    ('Alfa Romeo', 'mosolf_kippenheim'),
    ('Mercedes-Benz', 'neuhaus_gmbh_via_bald'),
    ('MG', 'carserviceerkens_wachtendonk'), ('MG', 'mosolf_wilhelmshaven'),
    ('BYD', 'mosolf_wilhelmshaven'),
    ('BMW', 'akb_kitzingen'), ('MINI', 'akb_kitzingen'),
    ('Dacia', 'blg_duisburg'), ('Renault', 'blg_duisburg'),
    ('Peugeot', 'mosolf_kippenheim'), ('Peugeot', 'mosolf_etzin'), ('Peugeot', 'siebrecht_uslar'),
    ('Citroen', 'mosolf_kippenheim'), ('DS', 'mosolf_kippenheim'),
    ('Opel', 'mosolf_etzin'), ('Opel', 'mosolf_kippenheim'), ('Opel', 'siebrecht_uslar'),
    ('Toyota', 'blg_saalanderdonau'),
    ('Seat', 'akb_zoerbig'), ('Cupra', 'akb_zoerbig'),
    ('Skoda', 'mosolf_rackwitz'),
    ('Audi', 'akb_kitzingen'),
]

# Build SQL filter
filter_tuples = ', '.join(f"('{b}', '{c}')" for b, c in COMPOUND_MAP)
print(f'{len(COMPOUND_MAP)} brand/compound combinations configured')

40 brand/compound combinations configured

## 2. Compound Lead Times — Avg & Median per Phase

In [3]:
lead_times_query = f"""
WITH events_all AS (
  SELECT
    e.car_id, e.name, e.time,
    JSON_VALUE(e.snapshot, '$.oem') AS oem,
    JSON_VALUE(e.snapshot, '$.infleeting_compound_id') AS compound_id
  FROM `datawarehouse-304513.cars_ops_postgres_public.car_events` e
  WHERE e.name IN (
    'car_ordered','car_state_changed_produced','car_state_changed_arrived_from_supplier',
    'car_state_changed_tech_prep_done','car_state_changed_ready_to_deliver','car_state_changed_in_subscription'
  )
),
cars_active_2025 AS (
  SELECT DISTINCT car_id FROM events_all
  WHERE time >= '2025-01-01' AND time < '2026-01-01'
),
filtered AS (
  SELECT e.* FROM events_all e
  INNER JOIN cars_active_2025 c ON e.car_id = c.car_id
),
state_changes AS (
  SELECT car_id, name, time, oem, compound_id,
    LAG(time) OVER (PARTITION BY car_id ORDER BY time) AS prev_time
  FROM filtered
),
with_days AS (
  SELECT *, DATE_DIFF(DATE(time), DATE(prev_time), DAY) AS days_in_status
  FROM state_changes WHERE prev_time IS NOT NULL
),
compound_lookup AS (
  SELECT DISTINCT car_id, compound_id FROM filtered
  WHERE name = 'car_state_changed_arrived_from_supplier' AND compound_id IS NOT NULL
)
SELECT
  d.oem AS brand,
  COALESCE(cl.compound_id, d.compound_id) AS compound,
  COUNT(DISTINCT d.car_id) AS cars,

  ROUND(AVG(IF(d.name='car_state_changed_produced', d.days_in_status, NULL)),1) AS avg_ordered_to_produced,
  APPROX_QUANTILES(IF(d.name='car_state_changed_produced', d.days_in_status, NULL), 100 IGNORE NULLS)[OFFSET(50)] AS med_ordered_to_produced,

  ROUND(AVG(IF(d.name='car_state_changed_arrived_from_supplier', d.days_in_status, NULL)),1) AS avg_produced_to_arrived,
  APPROX_QUANTILES(IF(d.name='car_state_changed_arrived_from_supplier', d.days_in_status, NULL), 100 IGNORE NULLS)[OFFSET(50)] AS med_produced_to_arrived,

  ROUND(AVG(IF(d.name='car_state_changed_tech_prep_done', d.days_in_status, NULL)),1) AS avg_arrived_to_techprep,
  APPROX_QUANTILES(IF(d.name='car_state_changed_tech_prep_done', d.days_in_status, NULL), 100 IGNORE NULLS)[OFFSET(50)] AS med_arrived_to_techprep,

  ROUND(AVG(IF(d.name='car_state_changed_ready_to_deliver', d.days_in_status, NULL)),1) AS avg_techprep_to_ready,
  APPROX_QUANTILES(IF(d.name='car_state_changed_ready_to_deliver', d.days_in_status, NULL), 100 IGNORE NULLS)[OFFSET(50)] AS med_techprep_to_ready,

  ROUND(AVG(IF(d.name='car_state_changed_in_subscription', d.days_in_status, NULL)),1) AS avg_ready_to_sub,
  APPROX_QUANTILES(IF(d.name='car_state_changed_in_subscription', d.days_in_status, NULL), 100 IGNORE NULLS)[OFFSET(50)] AS med_ready_to_sub

FROM with_days d
LEFT JOIN compound_lookup cl ON d.car_id = cl.car_id
WHERE (d.oem, COALESCE(cl.compound_id, d.compound_id)) IN ({filter_tuples})
GROUP BY 1, 2
ORDER BY brand, compound
"""

df = run_query(lead_times_query)
print(f'{len(df)} brand/compound combos, {df["cars"].sum():,} total car transitions')
df

40 brand/compound combos, 48,549 total car transitions

/Users/jan.heiselbetz/venvs/jupyter-py313/lib/python3.13/site-packages/google/cloud/bigquery/table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,brand,compound,cars,avg_ordered_to_produced,med_ordered_to_produced,avg_produced_to_arrived,med_produced_to_arrived,avg_arrived_to_techprep,med_arrived_to_techprep,avg_techprep_to_ready,med_techprep_to_ready,avg_ready_to_sub,med_ready_to_sub
0,Alfa Romeo,mosolf_kippenheim,268,180.0,188,10.5,0,18.0,2,66.3,32,27.3,18
1,Audi,akb_kitzingen,2484,139.3,124,67.7,68,25.0,19,23.5,7,12.3,8
2,BMW,akb_kitzingen,4446,31.5,28,88.9,85,13.8,2,16.7,9,10.8,8
3,BYD,mosolf_wilhelmshaven,3078,14.9,0,34.2,29,4.5,0,5.9,0,36.0,29
4,Cadillac,ceva_bad_salzungen,18,0.0,0,11.1,11,7.9,0,31.0,18,10.7,7
5,Cadillac,ceva_grevenbroich,16,0.0,0,22.1,24,10.9,0,42.9,49,6.0,7
6,Citroen,mosolf_kippenheim,795,125.2,116,14.4,1,6.8,5,13.4,13,20.0,15
7,Cupra,akb_zoerbig,1628,67.8,64,53.0,42,9.2,0,25.7,19,13.6,9
8,DS,mosolf_kippenheim,150,89.0,69,14.2,14,10.7,5,19.4,25,47.6,36
9,Dacia,blg_duisburg,2051,14.6,0,52.5,62,19.2,21,15.2,9,18.9,14
10,Fiat,mosolf_etzin,237,219.6,256,22.0,11,11.7,6,64.8,21,30.9,18
11,Fiat,mosolf_kippenheim,55,67.3,25,31.2,0,7.3,0,161.5,4,102.7,85
12,Ford,cat_zuelpich,515,20.0,8,34.8,26,21.9,20,32.2,28,12.3,8
13,Honda,akb_kitzingen,327,43.1,19,75.7,78,0.5,0,23.4,19,12.8,9
14,Hyundai,blg_bremerhaven,2853,21.4,0,45.4,36,32.4,27,28.1,21,13.8,9
15,Hyundai,mosolf_cuxhaven,997,39.4,2,42.9,30,28.6,36,21.5,14,12.3,9
16,Hyundai,mosolf_rackwitz,2315,64.9,40,28.7,13,30.5,25,27.9,21,12.7,9
17,Jeep,mosolf_etzin,442,166.0,202,22.9,13,8.9,4,85.3,33,50.1,43
18,Jeep,mosolf_goessnitz,270,36.9,26,24.5,15,18.5,12,22.4,13,66.2,65
19,Jeep,mosolf_kippenheim,620,91.2,69,21.7,4,21.3,13,102.2,78,49.7,29
20,Kia,blg_bremerhaven,610,5.7,0,21.9,21,20.1,17,41.7,32,13.7,9
21,Kia,blg_saalanderdonau,589,4.1,0,7.3,6,26.3,22,48.2,37,12.7,9
22,MG,carserviceerkens_wachtendonk,3120,53.5,24,31.8,13,12.1,0,17.6,6,76.3,27
23,MG,mosolf_wilhelmshaven,3610,62.8,51,31.1,33,12.3,0,13.9,2,35.6,24
24,MINI,akb_kitzingen,548,87.8,93,66.2,64,3.8,0,13.0,12,9.3,6
25,Mazda,blg_duisburg,470,101.6,82,22.3,13,69.1,63,20.5,10,20.2,9
26,Mazda,cat_zuelpich,1315,76.8,63,43.7,40,36.2,35,16.9,7,12.8,8
27,Mercedes-Benz,neuhaus_gmbh_via_bald,1037,70.6,69,43.1,37,18.6,16,17.4,11,12.8,8
28,Nissan,blg_neuss,1240,29.6,1,21.6,9,10.5,9,53.4,43,15.5,9
29,Opel,mosolf_etzin,2654,85.8,56,7.4,6,14.6,12,23.3,20,29.9,22
30,Opel,mosolf_kippenheim,481,72.0,56,17.3,21,9.5,5,21.1,20,21.9,17
31,Opel,siebrecht_uslar,470,157.7,93,12.9,10,9.9,3,80.0,20,57.2,27
32,Peugeot,mosolf_etzin,340,100.6,140,13.2,8,13.4,14,22.1,14,23.2,16
33,Peugeot,mosolf_kippenheim,1395,79.4,61,15.0,13,13.3,10,19.6,21,25.7,19
34,Peugeot,siebrecht_uslar,97,112.2,168,34.4,25,6.2,6,109.9,38,62.9,55
35,Polestar,cat_zuelpich,583,2.2,0,1.5,1,54.9,66,30.3,5,36.0,25
36,Renault,blg_duisburg,540,44.5,63,46.0,41,20.4,23,12.4,12,17.9,12
37,Seat,akb_zoerbig,370,104.5,101,36.4,33,24.7,21,24.0,18,14.2,10
38,Skoda,mosolf_rackwitz,2251,113.4,97,20.3,10,19.6,12,11.2,7,15.2,10
39,Toyota,blg_saalanderdonau,3264,61.3,54,28.3,17,20.1,15,47.3,31,15.5,9

## 3. Heatmap — Median Days per Phase

In [4]:
# Prepare heatmap data
df['label'] = df['brand'] + ' @ ' + df['compound'].str.replace('_', ' ')

phases = [
    ('med_ordered_to_produced', 'Ordered→Produced'),
    ('med_produced_to_arrived', 'Produced→Arrived'),
    ('med_arrived_to_techprep', 'Arrived→Tech Prep'),
    ('med_techprep_to_ready', 'Tech Prep→Ready'),
    ('med_ready_to_sub', 'Ready→Subscription'),
]

heat_df = df[['label', 'cars'] + [p[0] for p in phases]].copy()
heat_df.columns = ['label', 'cars'] + [p[1] for p in phases]

# Sort by total median days
phase_cols = [p[1] for p in phases]
heat_df['total'] = heat_df[phase_cols].sum(axis=1)
heat_df = heat_df.sort_values('total', ascending=True)

fig = px.imshow(
    heat_df[phase_cols].values,
    labels=dict(x='Phase', y='Brand @ Compound', color='Median Days'),
    x=phase_cols,
    y=heat_df['label'].values,
    color_continuous_scale='RdYlGn_r',
    aspect='auto',
    text_auto=True,
)
fig.update_layout(
    title='Infleeting Lead Times — Median Days per Phase (2025)',
    height=max(600, len(heat_df) * 22),
    width=900,
    font=dict(size=11),
)
fig.show()

## 4. Stacked Bar — Total Median Lead Time by Brand/Compound

In [5]:
# Stacked horizontal bar chart
bar_df = heat_df.sort_values('total', ascending=True).copy()

colors = {
    'Ordered→Produced': '#4e79a7',
    'Produced→Arrived': '#f28e2b',
    'Arrived→Tech Prep': '#e15759',
    'Tech Prep→Ready': '#76b7b2',
    'Ready→Subscription': '#59a14f',
}

fig = go.Figure()
for phase in phase_cols:
    fig.add_trace(go.Bar(
        y=bar_df['label'],
        x=bar_df[phase].fillna(0),
        name=phase,
        orientation='h',
        marker_color=colors[phase],
        text=bar_df[phase].fillna(0).astype(int),
        textposition='inside',
    ))

fig.update_layout(
    barmode='stack',
    title='Total Infleeting Lead Time — Median Days (2025)',
    xaxis_title='Days',
    height=max(600, len(bar_df) * 22),
    width=1000,
    legend=dict(orientation='h', yanchor='bottom', y=1.02),
    font=dict(size=11),
)
fig.show()

## 5. Avg vs Median Skew — Identifying Outlier-Heavy Combos

In [6]:
# Show where avg >> median (heavy right tail / outliers)
skew_data = []
for _, row in df.iterrows():
    for avg_col, med_col, phase_name in [
        ('avg_ordered_to_produced', 'med_ordered_to_produced', 'Ordered→Produced'),
        ('avg_produced_to_arrived', 'med_produced_to_arrived', 'Produced→Arrived'),
        ('avg_arrived_to_techprep', 'med_arrived_to_techprep', 'Arrived→Tech Prep'),
        ('avg_techprep_to_ready', 'med_techprep_to_ready', 'Tech Prep→Ready'),
        ('avg_ready_to_sub', 'med_ready_to_sub', 'Ready→Subscription'),
    ]:
        avg_val = row[avg_col]
        med_val = row[med_col]
        if pd.notna(avg_val) and pd.notna(med_val) and med_val > 0:
            skew_data.append({
                'brand': row['brand'],
                'compound': row['compound'],
                'phase': phase_name,
                'avg': avg_val,
                'median': med_val,
                'skew_ratio': round(avg_val / med_val, 1),
                'cars': row['cars'],
            })

skew_df = pd.DataFrame(skew_data)
print('Top 15 most skewed (avg/median ratio) — indicates outlier problems:')
skew_df.sort_values('skew_ratio', ascending=False).head(15)

Top 15 most skewed (avg/median ratio) — indicates outlier problems:

,brand,compound,phase,avg,median,skew_ratio,cars
46,Fiat,mosolf_kippenheim,Tech Prep→Ready,161.5,4,40.4,55
121,Nissan,blg_neuss,Ordered→Produced,29.6,1,29.6,1240
61,Hyundai,mosolf_cuxhaven,Ordered→Produced,39.4,2,19.7,997
23,Citroen,mosolf_kippenheim,Produced→Arrived,14.4,1,14.4,795
1,Alfa Romeo,mosolf_kippenheim,Arrived→Tech Prep,18.0,2,9.0,268
100,MG,mosolf_wilhelmshaven,Tech Prep→Ready,13.9,2,7.0,3610
11,BMW,akb_kitzingen,Arrived→Tech Prep,13.8,2,6.9,4446
158,Polestar,cat_zuelpich,Tech Prep→Ready,30.3,5,6.1,583
82,Jeep,mosolf_kippenheim,Produced→Arrived,21.7,4,5.4,620
139,Opel,siebrecht_uslar,Tech Prep→Ready,80.0,20,4.0,470
7,Audi,akb_kitzingen,Tech Prep→Ready,23.5,7,3.4,2484
138,Opel,siebrecht_uslar,Arrived→Tech Prep,9.9,3,3.3,470
43,Fiat,mosolf_etzin,Tech Prep→Ready,64.8,21,3.1,237
96,MG,carserviceerkens_wachtendonk,Tech Prep→Ready,17.6,6,2.9,3120
154,Peugeot,siebrecht_uslar,Tech Prep→Ready,109.9,38,2.9,97

## 6. Single Car Deep Dive

In [7]:
def car_deep_dive(car_id: str):
    """Fetch and display the full infleeting timeline for a single car."""
    query = f"""
    WITH state_changes AS (
      SELECT
        car_id, name, time,
        JSON_VALUE(snapshot, '$.oem') AS oem,
        JSON_VALUE(snapshot, '$.model') AS model,
        JSON_VALUE(snapshot, '$.infleeting_compound_id') AS compound_id,
        JSON_VALUE(snapshot, '$.status') AS status,
        LAG(time) OVER (ORDER BY time) AS prev_time,
        LAG(name) OVER (ORDER BY time) AS prev_name
      FROM `datawarehouse-304513.cars_ops_postgres_public.car_events`
      WHERE car_id = '{car_id}'
        AND name IN (
          'car_ordered','car_state_changed_produced','car_state_changed_arrived_from_supplier',
          'car_state_changed_tech_prep_done','car_state_changed_ready_to_deliver','car_state_changed_in_subscription'
        )
    )
    SELECT
      name AS event,
      time,
      oem, model, compound_id, status,
      DATE_DIFF(DATE(time), DATE(prev_time), DAY) AS days_in_prev_status
    FROM state_changes
    ORDER BY time
    """
    result = run_query(query)
    if len(result) == 0:
        print(f'No state change events found for car {car_id}')
        return None

    oem = result.iloc[0]['oem']
    model = result.iloc[0]['model']
    compound = result.iloc[-1]['compound_id']
    print(f'Car {car_id}: {oem} {model} @ {compound}')
    print(f'Total: {(result["time"].max() - result["time"].min()).days}d from ordered to {result.iloc[-1]["status"]}')
    print()
    return result[['event', 'time', 'days_in_prev_status', 'status']]

# Example: the Nissan Qashqai we analyzed earlier
car_deep_dive('zxmotnpu')

Car zxmotnpu: Nissan Qashqai @ blg_neuss
Total: 45d from ordered to in_subscription

/Users/jan.heiselbetz/venvs/jupyter-py313/lib/python3.13/site-packages/google/cloud/bigquery/table.py:1994: UserWarning:

BigQuery Storage module not found, fetch data with the REST endpoint instead.

,event,time,days_in_prev_status,status
0,car_ordered,2025-12-30 07:17:55.642000+00:00,<NA>,ordered
1,car_state_changed_produced,2025-12-30 07:17:55.869000+00:00,0,produced
2,car_state_changed_arrived_from_supplier,2026-01-07 06:18:54.461000+00:00,8,arrived_from_supplier
3,car_state_changed_tech_prep_done,2026-01-26 08:20:47.248000+00:00,19,tech_preparation_done
4,car_state_changed_ready_to_deliver,2026-02-02 08:00:55.471000+00:00,7,ready_to_deliver
5,car_state_changed_in_subscription,2026-02-13 09:53:59.273000+00:00,11,in_subscription

## 7. Monthly Trend — Fleet-Wide Throughput

In [8]:
trend_query = """
SELECT
  FORMAT_DATE('%Y-%m', DATE(time)) AS month,
  CASE name
    WHEN 'car_state_changed_produced' THEN 'Produced'
    WHEN 'car_state_changed_arrived_from_supplier' THEN 'Arrived'
    WHEN 'car_state_changed_tech_prep_done' THEN 'Tech Prep Done'
    WHEN 'car_state_changed_ready_to_deliver' THEN 'Ready to Deliver'
    WHEN 'car_state_changed_in_subscription' THEN 'In Subscription'
  END AS status,
  COUNT(DISTINCT car_id) AS cars
FROM `datawarehouse-304513.cars_ops_postgres_public.car_events`
WHERE name IN (
  'car_state_changed_produced','car_state_changed_arrived_from_supplier',
  'car_state_changed_tech_prep_done','car_state_changed_ready_to_deliver',
  'car_state_changed_in_subscription'
)
AND time >= '2025-01-01' AND time < '2026-01-01'
GROUP BY 1, 2
ORDER BY 1, 2
"""

trend_df = run_query(trend_query)

fig = px.line(
    trend_df, x='month', y='cars', color='status',
    title='Monthly Cars Reaching Each Infleeting Phase (2025)',
    labels={'cars': 'Cars', 'month': 'Month'},
    markers=True,
)
fig.update_layout(height=450, width=900, legend=dict(orientation='h', yanchor='bottom', y=1.02))
fig.show()

/Users/jan.heiselbetz/venvs/jupyter-py313/lib/python3.13/site-packages/google/cloud/bigquery/table.py:1994: UserWarning:

BigQuery Storage module not found, fetch data with the REST endpoint instead.

## 8. Bottleneck Detector — Worst Phases per Compound

In [9]:
# Find the worst phase for each brand/compound (highest median)
bottlenecks = []
for _, row in df.iterrows():
    worst_phase = None
    worst_val = 0
    for med_col, phase_name in [
        ('med_ordered_to_produced', 'Ordered→Produced'),
        ('med_produced_to_arrived', 'Produced→Arrived'),
        ('med_arrived_to_techprep', 'Arrived→Tech Prep'),
        ('med_techprep_to_ready', 'Tech Prep→Ready'),
        ('med_ready_to_sub', 'Ready→Subscription'),
    ]:
        val = row[med_col]
        if pd.notna(val) and val > worst_val:
            worst_val = val
            worst_phase = phase_name
    bottlenecks.append({
        'brand': row['brand'],
        'compound': row['compound'],
        'cars': row['cars'],
        'bottleneck_phase': worst_phase,
        'median_days': worst_val,
    })

bn_df = pd.DataFrame(bottlenecks).sort_values('median_days', ascending=False)

fig = px.bar(
    bn_df.head(20),
    x='median_days',
    y=bn_df.head(20).apply(lambda r: f"{r['brand']} @ {r['compound']}", axis=1),
    color='bottleneck_phase',
    orientation='h',
    title='Top 20 Bottlenecks — Worst Phase per Brand/Compound (Median Days)',
    labels={'median_days': 'Median Days', 'y': ''},
)
fig.update_layout(height=550, width=900, yaxis=dict(autorange='reversed'))
fig.show()

## 9. Expected vs. Actual Lead Times — Backtesting Accuracy

### How the API actually calculates `Available From`

The ops-cars API (`infleeting-lead-times.ts`) uses a **two-layer system**:

```
Available From = start_date + compound_lead_time_days
```

| Car Status | start_date | compound_lead_time | **Owner** |
|---|---|---|---|
| `ordered` / `produced` | **max(Fleet ETA, today)** | `OrderedLeadTimes` / `ProducedLeadTimes` | **Fleet** (ETA) + **Infleeting** (compound) |
| `arrived_from_supplier` | **today** (or anchor date) | `ArrivedFromSupplierLeadTimes` | **Infleeting** |
| `tech_prep_done` | **today** (or anchor date) | `TechPreparationDoneLeadTimes` | **Infleeting** |
| `ready_to_deliver` | **today** (or anchor date) | `ReadyToDeliverLeadTimes` | **Infleeting** |

### Two independent accuracy questions

1. **Fleet Layer (ETA accuracy)**: How long does `ordered → arrived_from_supplier` actually take? Fleet predicts this via OEM Delivery Plans. We don't have per-car ETA snapshots in BigQuery, but we CAN measure the actual duration distribution.

2. **Infleeting Layer (compound accuracy)**: How accurate is `t_arrived` (predicted days from compound arrival → subscription)? We CAN directly compare this against actual `arrived → in_subscription` medians.

### Why ordered = produced for most brands

For nearly every brand, `t_ordered = t_produced` (identical compound lead times). This means the API assumes **0 days of compound lead time difference** between ordered and produced — the real time between these states is entirely determined by Fleet ETA. Only Kia (56→42d) and Nissan (35→21d) have different values.

In [10]:
# API compound lead times (t-minus: remaining days until subscription from each status)
# Source: ops-cars-repo/src/domain/availabilities/lead-times/*.ts
# Using worst-case paths: unpaid, no SA number, outbound check not done
# Conversion: 1 week = 7 days, N working days ≈ ceil(N × 7/5) calendar days
#
# IMPORTANT: For ordered/produced, these values are NOT phase durations.
# They are compound processing times added to Fleet ETA: Available From = max(ETA, now) + t_value
# For arrived/techprep/ready, they ARE remaining days: Available From = now + t_value

API_LEAD_TIMES = [
    # (brand, compound, t_ordered, t_produced, t_arrived, t_techprep, t_ready, notes, source)
    # --- MAZDA (InfleetingProcess.MAZDA) ---
    ('Mazda', 'cat_zuelpich', 35, 35, 28, 28, 28, 'Unpaid; arrived=4w unpaid, techprep=4w unpaid, ready=4w mazda unpaid',
     'ordered:5w, produced:5w, arrived:getMazdaLeadTime(unpaid)=4w, techprep:AUDI/MAZDA(unpaid)=4w, ready:cat_zuelpich+MAZDA(unpaid)=4w'),
    ('Mazda', 'blg_duisburg', None, None, None, None, None, 'Only 1 car, no reference data', ''),
    # --- FORD (InfleetingProcess.PCDO) ---
    ('Ford', 'cat_zuelpich', 28, 28, 21, 14, 5, '',
     'ordered:PCDO=4w, produced:PCDO=4w, arrived:PCDO=3w, techprep:PCDO=wd(10)≈14d, ready:cat_zuelpich+PCDO=wd(3)≈5d'),
    # --- POLESTAR ---
    ('Polestar', 'cat_zuelpich', 35, 35, 21, 7, 5, '',
     'ordered:5w, produced:5w, arrived:POLESTAR=3w, techprep:POLESTAR=1w, ready:cat_zuelpich=wd(3)≈5d'),
    # --- HONDA (InfleetingProcess.MKM_HUBER) ---
    ('Honda', 'akb_kitzingen', 35, 35, 21, 10, 7, 'Outbound check not done',
     'ordered:MKM_HUBER=5w, produced:MKM_HUBER=5w, arrived:MKM_HUBER=3w, techprep:default=10d, ready:akb_kitzingen(no_outbound)=wd(5)≈7d'),
    # --- KIA ---
    ('Kia', 'blg_bremerhaven', 56, 42, 21, 10, 7, '',
     'ordered:KIA=8w, produced:KIA=6w, arrived:KIA=3w, techprep:default=10d, ready:blg_bremerhaven+KIA=wd(5)≈7d'),
    ('Kia', 'blg_saalanderdonau', 56, 42, 21, 10, 7, '',
     'ordered:KIA=8w, produced:KIA=6w, arrived:KIA=3w, techprep:default=10d, ready:blg_saalanderdonau+KIA=wd(5)≈7d'),
    # --- NISSAN (InfleetingProcess.MKM_HUBER) ---
    ('Nissan', 'blg_neuss', 35, 21, 21, 10, 7, '',
     'ordered:MKM_HUBER=5w, produced:MKM_HUBER+blg_neuss=3w, arrived:MKM_HUBER=3w, techprep:default=10d, ready:blg_neuss+MKM_HUBER=wd(5)≈7d'),
    # --- CADILLAC ---
    ('Cadillac', 'ceva_grevenbroich', 21, 21, 14, 10, 7, 'Outbound check not done',
     'ordered:CADILLAC=3w, produced:CADILLAC=3w, arrived:CADILLAC=14d, techprep:default=10d, ready:ceva+CADILLAC(no_outbound)=wd(5)≈7d'),
    ('Cadillac', 'ceva_bad_salzungen', 21, 21, 14, 10, 7, 'Outbound check not done',
     'ordered:CADILLAC=3w, produced:CADILLAC=3w, arrived:CADILLAC=14d, techprep:default=10d, ready:ceva+CADILLAC(no_outbound)=wd(5)≈7d'),
    # --- HYUNDAI ---
    ('Hyundai', 'blg_bremerhaven', 42, 42, 35, 10, 7, '',
     'ordered:HYUNDAI_VIA_BLG=6w, produced:HYUNDAI_VIA_BLG=6w, arrived:HYUNDAI_VIA_BLG=5w, techprep:default=10d, ready:blg_bremerhaven+HYUNDAI_BLG=wd(5)≈7d'),
    ('Hyundai', 'mosolf_rackwitz', 42, 42, 21, 10, 5, '',
     'ordered:HYUNDAI_VIA_MOSOLF=6w, produced:HYUNDAI_VIA_MOSOLF=6w, arrived:HYUNDAI_VIA_MOSOLF=3w, techprep:default=10d, ready:mosolf_rackwitz+HYUNDAI_MOSOLF=wd(3)≈5d'),
    ('Hyundai', 'mosolf_cuxhaven', 42, 42, 21, 10, 7, '',
     'ordered:HYUNDAI_VIA_MOSOLF=6w, produced:HYUNDAI_VIA_MOSOLF=6w, arrived:HYUNDAI_VIA_MOSOLF=3w, techprep:default=10d, ready:mosolf_cuxhaven+HYUNDAI_MOSOLF=wd(5)≈7d'),
    # --- FCA (Jeep, Fiat, Alfa Romeo) ---
    ('Jeep', 'mosolf_goessnitz', 21, 21, 21, 10, 9, 'No SA number',
     'ordered:FCA=3w, produced:FCA=3w, arrived:FCA=3w, techprep:default=10d, ready:mosolf no_SA=wd(6)≈9d'),
    ('Jeep', 'mosolf_kippenheim', 21, 21, 21, 10, 9, 'No SA number',
     'ordered:FCA=3w, produced:FCA=3w, arrived:FCA=3w, techprep:default=10d, ready:mosolf_kippenheim no_SA=wd(6)≈9d'),
    ('Jeep', 'mosolf_etzin', 21, 21, 21, 10, 9, 'No SA number',
     'ordered:FCA=3w, produced:FCA=3w, arrived:FCA=3w, techprep:default=10d, ready:mosolf_etzin no_SA=wd(6)≈9d'),
    ('Fiat', 'mosolf_kippenheim', 21, 21, 21, 10, 9, 'No SA number',
     'ordered:FCA=3w, produced:FCA=3w, arrived:FCA=3w, techprep:default=10d, ready:mosolf_kippenheim no_SA=wd(6)≈9d'),
    ('Fiat', 'mosolf_etzin', 21, 21, 21, 10, 9, 'No SA number',
     'ordered:FCA=3w, produced:FCA=3w, arrived:FCA=3w, techprep:default=10d, ready:mosolf_etzin no_SA=wd(6)≈9d'),
    ('Alfa Romeo', 'mosolf_kippenheim', 21, 21, 21, 10, 9, 'No SA number',
     'ordered:FCA=3w, produced:FCA=3w, arrived:FCA=3w, techprep:default=10d, ready:mosolf_kippenheim no_SA=wd(6)≈9d'),
    # --- MERCEDES ---
    ('Mercedes-Benz', 'neuhaus_gmbh_via_bald', 28, 28, 14, 21, 7, 'Unpaid path',
     'ordered:MERCEDES_BALD=4w, produced:MERCEDES_BALD=4w, arrived:MERCEDES_BALD=2w, techprep:MERCEDES_BALD(unpaid)=3w, ready:neuhaus+MERCEDES(unpaid)=3w→but wd(5)≈7d'),
    # --- MG ---
    ('MG', 'carserviceerkens_wachtendonk', 21, 21, 14, 10, 7, 'Often skips tech_prep',
     'ordered:MG=3w, produced:MG=3w, arrived:MG@erkens=2w, techprep:default=10d, ready:erkens+MG=wd(5)≈7d'),
    ('MG', 'mosolf_wilhelmshaven', 21, 21, 21, 10, 9, 'No SA; often skips tech_prep',
     'ordered:MG=3w, produced:MG=3w, arrived:MG@mosolf_whaven=3w, techprep:default=10d, ready:mosolf_whaven+MG no_SA=wd(6)≈9d'),
    # --- BYD ---
    ('BYD', 'mosolf_wilhelmshaven', 35, 35, 21, 10, 14, 'No SA + no release; often skips tech_prep',
     'ordered:BYD=5w, produced:BYD=5w, arrived:BYD=3w, techprep:default=10d, ready:mosolf_whaven+BYD no_SA no_release=wd(10)≈14d'),
    # --- BMW/MINI ---
    ('BMW', 'akb_kitzingen', 45, 45, 14, 10, 7, 'supplierStatus 170 default location; often skips tech_prep',
     'ordered:BMW@170=45d, produced:BMW@170=45d, arrived:BMW=2w, techprep:default=10d, ready:akb_kitzingen(no_outbound)=wd(5)≈7d'),
    ('MINI', 'akb_kitzingen', 45, 45, 14, 10, 7, 'supplierStatus 170 default; often skips tech_prep',
     'ordered:BMW@170=45d, produced:BMW@170=45d, arrived:BMW=2w, techprep:default=10d, ready:akb_kitzingen(no_outbound)=wd(5)≈7d'),
    # --- DACIA/RENAULT ---
    ('Dacia', 'blg_duisburg', 35, 35, 35, 14, 14, 'Unpaid path',
     'ordered:RENAULT=5w, produced:RENAULT=5w, arrived:getRenault(unpaid)=5w, techprep:RENAULT(unpaid)=2w, ready:blg_duisburg+RENAULT(unpaid)=2w'),
    ('Renault', 'blg_duisburg', 35, 35, 35, 14, 14, 'Unpaid path',
     'ordered:RENAULT=5w, produced:RENAULT=5w, arrived:getRenault(unpaid)=5w, techprep:RENAULT(unpaid)=2w, ready:blg_duisburg+RENAULT(unpaid)=2w'),
    # --- STELLANTIS (Peugeot, Citroen, DS, Opel) ---
    ('Peugeot', 'mosolf_kippenheim', 28, 28, 21, 9, 9, 'No SA number',
     'ordered:STELLANTIS=4w, produced:STELLANTIS=4w, arrived:STELLANTIS=3w, techprep:STELLANTIS=9d, ready:mosolf_kippenheim no_SA=wd(6)≈9d'),
    ('Peugeot', 'mosolf_etzin', 28, 28, 21, 9, 9, 'No SA number',
     'ordered:STELLANTIS=4w, produced:STELLANTIS=4w, arrived:STELLANTIS=3w, techprep:STELLANTIS=9d, ready:mosolf_etzin no_SA=wd(6)≈9d'),
    ('Peugeot', 'siebrecht_uslar', 28, 28, 21, 9, 7, '',
     'ordered:STELLANTIS=4w, produced:STELLANTIS=4w, arrived:STELLANTIS=3w, techprep:SIEBRECHT=9d, ready:default=1w'),
    ('Citroen', 'mosolf_kippenheim', 28, 28, 21, 9, 9, 'No SA number',
     'ordered:STELLANTIS=4w, produced:STELLANTIS=4w, arrived:STELLANTIS=3w, techprep:STELLANTIS=9d, ready:mosolf_kippenheim no_SA=wd(6)≈9d'),
    ('DS', 'mosolf_kippenheim', 28, 28, 21, 9, 9, 'No SA number',
     'ordered:STELLANTIS=4w, produced:STELLANTIS=4w, arrived:STELLANTIS=3w, techprep:STELLANTIS=9d, ready:mosolf_kippenheim no_SA=wd(6)≈9d'),
    ('Opel', 'mosolf_etzin', 28, 28, 21, 9, 9, 'No SA number',
     'ordered:STELLANTIS=4w, produced:STELLANTIS=4w, arrived:STELLANTIS=3w, techprep:STELLANTIS=9d, ready:mosolf_etzin no_SA=wd(6)≈9d'),
    ('Opel', 'mosolf_kippenheim', 28, 28, 21, 9, 9, 'No SA number',
     'ordered:STELLANTIS=4w, produced:STELLANTIS=4w, arrived:STELLANTIS=3w, techprep:STELLANTIS=9d, ready:mosolf_kippenheim no_SA=wd(6)≈9d'),
    ('Opel', 'siebrecht_uslar', 28, 28, 21, 9, 7, '',
     'ordered:STELLANTIS=4w, produced:STELLANTIS=4w, arrived:STELLANTIS=3w, techprep:SIEBRECHT=9d, ready:default=1w'),
    # --- TOYOTA ---
    ('Toyota', 'blg_saalanderdonau', 28, 28, 21, 10, 7, '',
     'ordered:TOYOTA=4w, produced:TOYOTA=4w, arrived:TOYOTA=3w, techprep:default=10d, ready:blg_saalanderdonau+TOYOTA=wd(5)≈7d'),
    # --- VW GROUP (FESER / FESER_SEAT_ILLINGEN / SKODA_VIA_AH_KOCH / AUDI) ---
    ('Seat', 'akb_zoerbig', 49, 49, 35, 28, 7, 'Unpaid; outbound not done',
     'ordered:FESER_SEAT(unpaid)=7w, produced:FESER_SEAT(unpaid)=7w, arrived:FESER_SEAT(unpaid)=5w, techprep:FESER_SEAT(unpaid)=4w, ready:akb_zoerbig(no_outbound)=wd(5)≈7d'),
    ('Cupra', 'akb_zoerbig', 49, 49, 35, 28, 7, 'Unpaid; outbound not done',
     'ordered:FESER_SEAT(unpaid)=7w, produced:FESER_SEAT(unpaid)=7w, arrived:FESER_SEAT(unpaid)=5w, techprep:FESER_SEAT(unpaid)=4w, ready:akb_zoerbig(no_outbound)=wd(5)≈7d'),
    ('Skoda', 'mosolf_rackwitz', 49, 49, 35, 28, 5, 'Unpaid',
     'ordered:SKODA_AH_KOCH(unpaid)=7w, produced:SKODA_AH_KOCH(unpaid)=7w, arrived:SKODA_AH_KOCH(unpaid)=5w, techprep:SKODA_AH_KOCH(unpaid)=4w, ready:mosolf_rackwitz=wd(3)≈5d'),
    ('Audi', 'akb_kitzingen', 49, 49, 35, 21, 7, 'Unpaid; outbound not done',
     'ordered:AUDI(unpaid)=7w, produced:AUDI(unpaid)=7w, arrived:AUDI(unpaid)=5w→but getAudiLeadTime=5w=35d→wait techprep:AUDI(unpaid)=4w→but 3w=21d, ready:akb_kitzingen(no_outbound)=wd(5)≈7d'),
]

# Build t-minus DataFrame
tminus_df = pd.DataFrame(API_LEAD_TIMES, columns=[
    'brand', 'compound',
    't_ordered', 't_produced', 't_arrived', 't_techprep', 't_ready',
    'notes', 'api_source'
])

# Derive expected phase durations from t-minus differences
has_data = tminus_df['t_ordered'].notna()
tminus_valid = tminus_df[has_data].copy()

# Phase duration = t_minus[current] - t_minus[next]; last phase = t_ready itself
tminus_valid['exp_ordered_to_produced'] = tminus_valid['t_ordered'] - tminus_valid['t_produced']
tminus_valid['exp_produced_to_arrived'] = tminus_valid['t_produced'] - tminus_valid['t_arrived']
tminus_valid['exp_arrived_to_techprep'] = tminus_valid['t_arrived'] - tminus_valid['t_techprep']
tminus_valid['exp_techprep_to_ready'] = tminus_valid['t_techprep'] - tminus_valid['t_ready']
tminus_valid['exp_ready_to_sub'] = tminus_valid['t_ready']

# NOTE: exp_ordered_to_produced = 0 for most brands because ordered/produced
# have the same compound lead time. This is BY DESIGN — the API doesn't predict
# OEM production time; it relies on Fleet ETA for that.

exp_cols = ['brand', 'compound',
    'exp_ordered_to_produced', 'exp_produced_to_arrived',
    'exp_arrived_to_techprep', 'exp_techprep_to_ready', 'exp_ready_to_sub',
    'notes',
    't_ordered', 't_produced', 't_arrived', 't_techprep', 't_ready']

no_data = tminus_df[~has_data][['brand', 'compound', 'notes',
    't_ordered', 't_produced', 't_arrived', 't_techprep', 't_ready']].copy()
for col in ['exp_ordered_to_produced', 'exp_produced_to_arrived',
            'exp_arrived_to_techprep', 'exp_techprep_to_ready', 'exp_ready_to_sub']:
    no_data[col] = None

expected_df = pd.concat([tminus_valid[exp_cols], no_data[exp_cols]], ignore_index=True)

print(f'{len(expected_df)} brand/compound combinations with API lead times')
print(f'\nKey: t_ordered/t_produced = compound lead time added to ETA')
print(f'     t_arrived/t_techprep/t_ready = remaining days to subscription from today')
print(f'\nBrands where ordered ≠ produced (API gives different values):')
diff = tminus_valid[tminus_valid['t_ordered'] != tminus_valid['t_produced']]
if len(diff) > 0:
    print(diff[['brand', 'compound', 't_ordered', 't_produced']].to_string(index=False))
else:
    print('  None — all brands have identical ordered/produced values')

print(f'\nDerived phase durations (t-minus differences):')
expected_df[expected_df['exp_ordered_to_produced'].notna()][
    ['brand', 'compound', 'exp_ordered_to_produced', 'exp_produced_to_arrived',
     'exp_arrived_to_techprep', 'exp_techprep_to_ready', 'exp_ready_to_sub']
].head(15)

40 brand/compound combinations with API lead times

Key: t_ordered/t_produced = compound lead time added to ETA
     t_arrived/t_techprep/t_ready = remaining days to subscription from today

Brands where ordered ≠ produced (API gives different values):
 brand           compound  t_ordered  t_produced
   Kia    blg_bremerhaven       56.0        42.0
   Kia blg_saalanderdonau       56.0        42.0
Nissan          blg_neuss       35.0        21.0

Derived phase durations (t-minus differences):

/var/folders/b7/bv1g5g0x1wz5cw6rkjcwgz7w0000gp/T/ipykernel_54473/4161481108.py:144: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

,brand,compound,exp_ordered_to_produced,exp_produced_to_arrived,exp_arrived_to_techprep,exp_techprep_to_ready,exp_ready_to_sub
0,Mazda,cat_zuelpich,0.0,7.0,0.0,0.0,28.0
1,Ford,cat_zuelpich,0.0,7.0,7.0,9.0,5.0
2,Polestar,cat_zuelpich,0.0,14.0,14.0,2.0,5.0
3,Honda,akb_kitzingen,0.0,14.0,11.0,3.0,7.0
4,Kia,blg_bremerhaven,14.0,21.0,11.0,3.0,7.0
5,Kia,blg_saalanderdonau,14.0,21.0,11.0,3.0,7.0
6,Nissan,blg_neuss,14.0,0.0,11.0,3.0,7.0
7,Cadillac,ceva_grevenbroich,0.0,7.0,4.0,3.0,7.0
8,Cadillac,ceva_bad_salzungen,0.0,7.0,4.0,3.0,7.0
9,Hyundai,blg_bremerhaven,0.0,7.0,25.0,3.0,7.0
10,Hyundai,mosolf_rackwitz,0.0,21.0,11.0,5.0,5.0
11,Hyundai,mosolf_cuxhaven,0.0,21.0,11.0,3.0,7.0
12,Jeep,mosolf_goessnitz,0.0,0.0,11.0,1.0,9.0
13,Jeep,mosolf_kippenheim,0.0,0.0,11.0,1.0,9.0
14,Jeep,mosolf_etzin,0.0,0.0,11.0,1.0,9.0

### 9.1 Fleet Layer — Ordered→Arrived Duration (Fleet-owned, no ETA data available)

The Fleet team owns the ETA prediction: how long from `ordered` (or `produced`) until the car physically arrives at the compound (`arrived_from_supplier`). We **cannot** directly measure ETA accuracy because per-car ETA snapshots aren't in `car_events`. But we CAN show:

1. **Actual median days** for ordered→arrived per brand/compound (how long Fleet's phase actually takes)
2. **Variance** (how predictable is the Fleet phase?)
3. **Which brands dominate total prediction error** via the Fleet phase

In [11]:
# === FLEET LAYER: Ordered → Arrived duration analysis ===
# This measures how long the Fleet-owned phase actually takes (not ETA accuracy, since we lack ETA data)

fleet_data = df.copy()
fleet_data['actual_ordered_to_arrived'] = (
    fleet_data['med_ordered_to_produced'].fillna(0) +
    fleet_data['med_produced_to_arrived'].fillna(0)
)
fleet_data['actual_arrived_to_sub'] = (
    fleet_data['med_arrived_to_techprep'].fillna(0) +
    fleet_data['med_techprep_to_ready'].fillna(0) +
    fleet_data['med_ready_to_sub'].fillna(0)
)
fleet_data['actual_total'] = fleet_data['actual_ordered_to_arrived'] + fleet_data['actual_arrived_to_sub']
fleet_data['fleet_pct_of_total'] = (fleet_data['actual_ordered_to_arrived'] / fleet_data['actual_total'] * 100).round(1)
fleet_data['label'] = fleet_data['brand'] + ' @ ' + fleet_data['compound'].str.replace('_', ' ')

# Sort by Fleet phase duration
fleet_sorted = fleet_data.sort_values('actual_ordered_to_arrived', ascending=True)

print('=== FLEET LAYER: Actual Ordered→Arrived Duration (median days) ===')
print('Fleet owns ETA prediction. We cannot compare against predicted ETA (not in car_events).')
print('But we CAN show how long this phase actually takes and how much of the total it represents.\n')

print(f'{"Brand":<20} {"Compound":<30} {"Ord→Arr":>8} {"Arr→Sub":>8} {"Total":>8} {"Fleet %":>8}')
print('-' * 82)
for _, r in fleet_sorted.iterrows():
    fleet_flag = ' ⚠️' if r['fleet_pct_of_total'] > 70 else ''
    print(f'{r["brand"]:<20} {r["compound"]:<30} {r["actual_ordered_to_arrived"]:>7.0f}d {r["actual_arrived_to_sub"]:>7.0f}d {r["actual_total"]:>7.0f}d {r["fleet_pct_of_total"]:>7.1f}%{fleet_flag}')

print(f'\n⚠️ = Fleet phase is >70% of total lifecycle (ETA accuracy dominates)')
print(f'\nFleet phase stats:')
print(f'  Mean: {fleet_data["actual_ordered_to_arrived"].mean():.0f}d')
print(f'  Median: {fleet_data["actual_ordered_to_arrived"].median():.0f}d')
print(f'  Max: {fleet_data["actual_ordered_to_arrived"].max():.0f}d (worst brand for Fleet prediction)')
print(f'  Brands where Fleet >70% of total: {(fleet_data["fleet_pct_of_total"] > 70).sum()} / {len(fleet_data)}')

# Horizontal bar chart: Fleet vs Infleeting breakdown
import plotly.graph_objects as go

fig = go.Figure()
fig.add_trace(go.Bar(
    y=fleet_sorted['label'], x=fleet_sorted['actual_ordered_to_arrived'],
    name='Fleet Phase (ordered→arrived)', orientation='h',
    marker_color='#e45756', text=fleet_sorted['actual_ordered_to_arrived'].round(0).astype(int),
    textposition='inside'
))
fig.add_trace(go.Bar(
    y=fleet_sorted['label'], x=fleet_sorted['actual_arrived_to_sub'],
    name='Infleeting Phase (arrived→subscription)', orientation='h',
    marker_color='#4c78a8', text=fleet_sorted['actual_arrived_to_sub'].round(0).astype(int),
    textposition='inside'
))
fig.update_layout(
    barmode='stack', title='Fleet vs Infleeting: Who Owns the Lifecycle Time?',
    xaxis_title='Median Days', height=max(500, len(fleet_sorted) * 22),
    legend=dict(orientation='h', yanchor='bottom', y=1.02),
    margin=dict(l=250)
)
fig.show()

# Skew analysis for Fleet phase
print('\n=== FLEET PHASE SKEW (avg/median ratio) ===')
print('High skew = most cars fast, but outliers stuck for weeks/months\n')
fleet_skew = fleet_data.copy()
fleet_skew['avg_ordered_to_arrived'] = (
    fleet_skew['avg_ordered_to_produced'].fillna(0) +
    fleet_skew['avg_produced_to_arrived'].fillna(0)
)
fleet_skew['skew'] = (fleet_skew['avg_ordered_to_arrived'] / fleet_skew['actual_ordered_to_arrived']).round(1)
fleet_skew = fleet_skew[fleet_skew['actual_ordered_to_arrived'] > 0].sort_values('skew', ascending=False)
high_skew = fleet_skew[fleet_skew['skew'] > 3]
if len(high_skew) > 0:
    print(f'Brands with skew > 3x (avg >> median):')
    for _, r in high_skew.iterrows():
        print(f'  {r["brand"]:<20} @ {r["compound"]:<25} avg={r["avg_ordered_to_arrived"]:.0f}d, med={r["actual_ordered_to_arrived"]:.0f}d, skew={r["skew"]}x')
else:
    print('No brands with extreme skew (>3x) in Fleet phase')

=== FLEET LAYER: Actual Ordered→Arrived Duration (median days) ===
Fleet owns ETA prediction. We cannot compare against predicted ETA (not in car_events).
But we CAN show how long this phase actually takes and how much of the total it represents.

Brand                Compound                        Ord→Arr  Arr→Sub    Total  Fleet %
----------------------------------------------------------------------------------
Polestar             cat_zuelpich                         1d      96d      97d     1.0%
Kia                  blg_saalanderdonau                   6d      68d      74d     8.1%
Nissan               blg_neuss                           10d      61d      71d    14.1%
Cadillac             ceva_bad_salzungen                  11d      25d      36d    30.6%
Kia                  blg_bremerhaven                     21d      58d      79d    26.6%
Cadillac             ceva_grevenbroich                   24d      56d      80d    30.0%
Fiat                 mosolf_kippenheim                   25d      89d     114d    21.9%
BYD                  mosolf_wilhelmshaven                29d      29d      58d    50.0%
Hyundai              mosolf_cuxhaven                     32d      59d      91d    35.2%
Ford                 cat_zuelpich                        34d      56d      90d    37.8%
Hyundai              blg_bremerhaven                     36d      57d      93d    38.7%
MG                   carserviceerkens_wachtendonk        37d      33d      70d    52.9%
Jeep                 mosolf_goessnitz                    41d      90d     131d    31.3%
Hyundai              mosolf_rackwitz                     53d      55d     108d    49.1%
Opel                 mosolf_etzin                        62d      54d     116d    53.4%
Dacia                blg_duisburg                        62d      44d     106d    58.5%
Toyota               blg_saalanderdonau                  71d      55d     126d    56.3%
Jeep                 mosolf_kippenheim                   73d     120d     193d    37.8%
Peugeot              mosolf_kippenheim                   74d      50d     124d    59.7%
Opel                 mosolf_kippenheim                   77d      42d     119d    64.7%
DS                   mosolf_kippenheim                   83d      66d     149d    55.7%
MG                   mosolf_wilhelmshaven                84d      26d     110d    76.4% ⚠️
Mazda                blg_duisburg                        95d      82d     177d    53.7%
Honda                akb_kitzingen                       97d      28d     125d    77.6% ⚠️
Mazda                cat_zuelpich                       103d      50d     153d    67.3%
Opel                 siebrecht_uslar                    103d      50d     153d    67.3%
Renault              blg_duisburg                       104d      47d     151d    68.9%
Cupra                akb_zoerbig                        106d      28d     134d    79.1% ⚠️
Mercedes-Benz        neuhaus_gmbh_via_bald              106d      35d     141d    75.2% ⚠️
Skoda                mosolf_rackwitz                    107d      29d     136d    78.7% ⚠️
BMW                  akb_kitzingen                      113d      19d     132d    85.6% ⚠️
Citroen              mosolf_kippenheim                  117d      33d     150d    78.0% ⚠️
Seat                 akb_zoerbig                        134d      49d     183d    73.2% ⚠️
Peugeot              mosolf_etzin                       148d      44d     192d    77.1% ⚠️
MINI                 akb_kitzingen                      157d      18d     175d    89.7% ⚠️
Alfa Romeo           mosolf_kippenheim                  188d      52d     240d    78.3% ⚠️
Audi                 akb_kitzingen                      192d      34d     226d    85.0% ⚠️
Peugeot              siebrecht_uslar                    193d      99d     292d    66.1%
Jeep                 mosolf_etzin                       215d      80d     295d    72.9% ⚠️
Fiat                 mosolf_etzin                       267d      45d     312d    85.6% ⚠️

⚠️ = Fleet phase is >70% of total lifecycle (ETA accuracy dominates)

Fleet phase stats:
  Mean: 87d
  Median: 80d
  Max: 267d (worst brand for Fleet prediction)
  Brands where Fleet >70% of total: 14 / 40

=== FLEET PHASE SKEW (avg/median ratio) ===
High skew = most cars fast, but outliers stuck for weeks/months

Brands with skew > 3x (avg >> median):
  Nissan               @ blg_neuss                 avg=51d, med=10d, skew=5.1x
  Fiat                 @ mosolf_kippenheim         avg=98d, med=25d, skew=3.9x
  Polestar             @ cat_zuelpich              avg=4d, med=1d, skew=3.7x

### 9.2 Infleeting Layer — Compound Lead Time Accuracy (Infleeting-owned)

The API's compound lead time (`t_arrived`) predicts how many days from compound arrival until subscription.  
This is **Infleeting's responsibility** and the only comparison that directly measures compound processing prediction quality.  
The ordered/produced predictions additionally depend on Fleet ETA accuracy (section 9.1).

In [12]:
# === PART 1: Compound lead time accuracy (arrived → subscription) ===
# This is the meaningful comparison: API t_arrived vs actual total days from arrival to subscription

comparison = df.merge(expected_df, on=['brand', 'compound'], how='left')

# Compute actual arrived→subscription (sum of arrived→techprep + techprep→ready + ready→sub)
comparison['actual_arrived_to_sub'] = (
    comparison['med_arrived_to_techprep'].fillna(0) +
    comparison['med_techprep_to_ready'].fillna(0) +
    comparison['med_ready_to_sub'].fillna(0)
)

compound_accuracy = comparison[comparison['t_arrived'].notna()].copy()
compound_accuracy['delta_compound'] = compound_accuracy['actual_arrived_to_sub'] - compound_accuracy['t_arrived']
compound_accuracy['pct_error_compound'] = (compound_accuracy['delta_compound'] / compound_accuracy['t_arrived'] * 100).round(1)
compound_accuracy['label'] = compound_accuracy['brand'] + ' @ ' + compound_accuracy['compound']

print('=== COMPOUND LEAD TIME ACCURACY (t_arrived vs actual arrived→subscription) ===\n')
print(f'Comparisons: {len(compound_accuracy)}')
print(f'Mean absolute error: {compound_accuracy["delta_compound"].abs().mean():.1f} days')
print(f'Accurate (within ±20%): {(compound_accuracy["pct_error_compound"].abs() <= 20).sum()} / {len(compound_accuracy)} ({(compound_accuracy["pct_error_compound"].abs() <= 20).mean()*100:.0f}%)')
print(f'Faster than predicted: {(compound_accuracy["delta_compound"] < 0).sum()}')
print(f'Slower than predicted: {(compound_accuracy["delta_compound"] > 0).sum()}')

print(f'\nTop 15 compound lead time misses:')
compound_misses = compound_accuracy.sort_values('delta_compound', key=abs, ascending=False).head(15)
compound_misses[['brand', 'compound', 't_arrived', 'actual_arrived_to_sub', 'delta_compound', 'pct_error_compound', 'cars']]

=== COMPOUND LEAD TIME ACCURACY (t_arrived vs actual arrived→subscription) ===

Comparisons: 39
Mean absolute error: 30.1 days
Accurate (within ±20%): 3 / 39 (8%)
Faster than predicted: 3
Slower than predicted: 36

Top 15 compound lead time misses:

,brand,compound,t_arrived,actual_arrived_to_sub,delta_compound,pct_error_compound,cars
19,Jeep,mosolf_kippenheim,21.0,120,99.0,471.4,620
34,Peugeot,siebrecht_uslar,21.0,99,78.0,371.4,97
35,Polestar,cat_zuelpich,21.0,96,75.0,357.1,583
18,Jeep,mosolf_goessnitz,21.0,90,69.0,328.6,270
11,Fiat,mosolf_kippenheim,21.0,89,68.0,323.8,55
17,Jeep,mosolf_etzin,21.0,80,59.0,281.0,442
21,Kia,blg_saalanderdonau,21.0,68,47.0,223.8,589
8,DS,mosolf_kippenheim,21.0,66,45.0,214.3,150
5,Cadillac,ceva_grevenbroich,14.0,56,42.0,300.0,16
28,Nissan,blg_neuss,21.0,61,40.0,190.5,1240
15,Hyundai,mosolf_cuxhaven,21.0,59,38.0,181.0,997
20,Kia,blg_bremerhaven,21.0,58,37.0,176.2,610
12,Ford,cat_zuelpich,21.0,56,35.0,166.7,515
16,Hyundai,mosolf_rackwitz,21.0,55,34.0,161.9,2315
39,Toyota,blg_saalanderdonau,21.0,55,34.0,161.9,3264

### 9.3 Infleeting Layer — Compound Lead Time Heatmap (API t_arrived vs Actual)

In [13]:
# Compound lead time heatmap: API prediction vs reality
ca = compound_accuracy.sort_values('delta_compound', ascending=True).copy()

fig = go.Figure()
fig.add_trace(go.Bar(
    y=ca['label'], x=ca['t_arrived'], name='API t_arrived (predicted)',
    orientation='h', marker_color='#4e79a7', opacity=0.7,
))
fig.add_trace(go.Bar(
    y=ca['label'], x=ca['actual_arrived_to_sub'], name='Actual arrived→sub (median)',
    orientation='h', marker_color='#e15759', opacity=0.7,
))
fig.update_layout(
    barmode='group',
    title='Compound Lead Time: API Prediction vs Reality (arrived→subscription)',
    xaxis_title='Days',
    height=max(600, len(ca) * 25),
    width=1000,
    legend=dict(orientation='h', yanchor='bottom', y=1.02),
)
fig.show()

# Also show the delta as a diverging bar
fig2 = go.Figure()
colors = ['#e15759' if d > 0 else '#4e79a7' for d in ca['delta_compound']]
fig2.add_trace(go.Bar(
    y=ca['label'], x=ca['delta_compound'],
    orientation='h', marker_color=colors,
    text=ca['delta_compound'].apply(lambda x: f'+{x:.0f}d' if x > 0 else f'{x:.0f}d'),
    textposition='outside',
))
fig2.update_layout(
    title='Compound Lead Time Error (actual − predicted)<br><sub>Red = slower than predicted, Blue = faster</sub>',
    xaxis_title='Delta (days)',
    height=max(600, len(ca) * 25),
    width=900,
)
fig2.show()

### 9.4 Per-Phase Accuracy (derived phase durations from t-minus differences)

**Ownership split**:
- `Ordered→Produced` and `Produced→Arrived`: **Fleet-owned** — derived expected = 0 for most brands because the API relies on Fleet ETA, not compound lead times
- `Arrived→Tech Prep`, `Tech Prep→Ready`, `Ready→Subscription`: **Infleeting-owned** — these are directly controlled by hardcoded compound lead times

Large deltas in Fleet phases are ETA accuracy problems. Large deltas in Infleeting phases are compound lead time errors we can fix.

In [14]:
# Per-phase accuracy using derived phase durations (t-minus differences)
phase_mappings = [
    ('med_ordered_to_produced', 'exp_ordered_to_produced', 'Ordered→Produced'),
    ('med_produced_to_arrived', 'exp_produced_to_arrived', 'Produced→Arrived'),
    ('med_arrived_to_techprep', 'exp_arrived_to_techprep', 'Arrived→Tech Prep'),
    ('med_techprep_to_ready', 'exp_techprep_to_ready', 'Tech Prep→Ready'),
    ('med_ready_to_sub', 'exp_ready_to_sub', 'Ready→Subscription'),
]

accuracy_rows = []
for _, row in comparison.iterrows():
    if pd.isna(row.get('exp_ordered_to_produced')):
        continue
    for actual_col, expected_col, phase_name in phase_mappings:
        actual = row[actual_col]
        expected = row[expected_col]
        if pd.notna(actual) and pd.notna(expected) and expected > 0:
            delta = actual - expected
            pct_error = (delta / expected) * 100
            accuracy_rows.append({
                'brand': row['brand'], 'compound': row['compound'],
                'phase': phase_name, 'expected_days': expected,
                'actual_median': actual, 'delta_days': delta,
                'pct_error': round(pct_error, 1), 'cars': row['cars'],
            })

accuracy_df = pd.DataFrame(accuracy_rows)

# Phase accuracy summary
phase_order = ['Ordered→Produced', 'Produced→Arrived', 'Arrived→Tech Prep', 'Tech Prep→Ready', 'Ready→Subscription']
phase_acc = accuracy_df.groupby('phase').agg({
    'delta_days': ['mean', 'std', lambda x: x.abs().mean()],
    'pct_error': ['mean', lambda x: x.abs().mean()],
}).round(1)
phase_acc.columns = ['mean_delta', 'std_delta', 'mae_days', 'mean_pct_error', 'mape']
phase_acc = phase_acc.reindex([p for p in phase_order if p in phase_acc.index])

print('=== PER-PHASE ACCURACY (derived from t-minus differences) ===\n')
print('⚠️  Ordered→Produced: expected=0 for most brands (API has same ordered/produced values)')
print('    Non-zero only for Kia (14d) and Nissan (14d) where API values differ.\n')
phase_acc

=== PER-PHASE ACCURACY (derived from t-minus differences) ===

⚠️  Ordered→Produced: expected=0 for most brands (API has same ordered/produced values)
    Non-zero only for Kia (14d) and Nissan (14d) where API values differ.

                    mean_delta  std_delta  mae_days  mean_pct_error    mape
phase
Ordered→Produced         -13.7        0.6      13.7           -97.6    97.6
Produced→Arrived          14.4       19.6      17.7           132.0   154.8
Arrived→Tech Prep          0.8       11.9       7.8            -0.1    79.6
Tech Prep→Ready           17.0       19.1      19.1          1010.9  1022.3
Ready→Subscription        10.9       17.5      12.1           139.5   144.6

### 9.5 Accuracy Heatmap — Per-Phase Delta (actual − expected)

In [15]:
# Per-phase heatmap (only phases where expected > 0)
accuracy_pivot = accuracy_df.pivot_table(
    index=['brand', 'compound'], columns='phase', values='delta_days', aggfunc='first'
)
phase_order_available = [p for p in phase_order if p in accuracy_pivot.columns]
accuracy_pivot = accuracy_pivot[phase_order_available]
accuracy_pivot_labels = [f'{b} @ {c}' for b, c in accuracy_pivot.index]

fig = px.imshow(
    accuracy_pivot.values,
    labels=dict(x='Phase', y='Brand @ Compound', color='Delta (days)'),
    x=accuracy_pivot.columns.tolist(),
    y=accuracy_pivot_labels,
    color_continuous_scale='RdBu_r',
    color_continuous_midpoint=0,
    aspect='auto', text_auto=True,
)
fig.update_layout(
    title='Per-Phase Prediction Error: Actual − Expected (days)<br><sub>Red = slower than predicted, Blue = faster | Ordered→Produced only shows Kia/Nissan (others have expected=0)</sub>',
    height=max(600, len(accuracy_pivot) * 22),
    width=950, font=dict(size=11),
)
fig.show()

### 9.6 Recommendations — Compound Lead Times to Update (Infleeting-owned)

Ranked by impact: absolute error × volume. Only includes **Infleeting-owned** comparisons (arrived→subscription) where the API value is directly actionable by Infleeting.

In [16]:
# Recommendations: compound lead time updates ranked by impact
recs = compound_accuracy[compound_accuracy['delta_compound'].abs() > 3].copy()
recs['abs_delta'] = recs['delta_compound'].abs()
recs['impact'] = recs['abs_delta'] * recs['cars']  # days-off × volume
recs = recs.sort_values('impact', ascending=False)

recs['direction'] = recs['delta_compound'].apply(lambda d: 'SLOWER than predicted' if d > 0 else 'FASTER than predicted')
recs['recommendation'] = recs.apply(
    lambda r: f"t_arrived: {int(r['t_arrived'])}d → {int(r['actual_arrived_to_sub'])}d", axis=1
)

print(f'Compound lead times needing updates (>3d off): {len(recs)}\n')
print('Top 20 by impact (error × volume):\n')
recs[['brand', 'compound', 't_arrived', 'actual_arrived_to_sub', 'delta_compound', 
      'direction', 'cars', 'recommendation']].head(20)

Compound lead times needing updates (>3d off): 38

Top 20 by impact (error × volume):

,brand,compound,t_arrived,actual_arrived_to_sub,delta_compound,direction,cars,recommendation
39,Toyota,blg_saalanderdonau,21.0,55,34.0,SLOWER than predicted,3264,t_arrived: 21d → 55d
29,Opel,mosolf_etzin,21.0,54,33.0,SLOWER than predicted,2654,t_arrived: 21d → 54d
16,Hyundai,mosolf_rackwitz,21.0,55,34.0,SLOWER than predicted,2315,t_arrived: 21d → 55d
14,Hyundai,blg_bremerhaven,35.0,57,22.0,SLOWER than predicted,2853,t_arrived: 35d → 57d
19,Jeep,mosolf_kippenheim,21.0,120,99.0,SLOWER than predicted,620,t_arrived: 21d → 120d
22,MG,carserviceerkens_wachtendonk,14.0,33,19.0,SLOWER than predicted,3120,t_arrived: 14d → 33d
28,Nissan,blg_neuss,21.0,61,40.0,SLOWER than predicted,1240,t_arrived: 21d → 61d
35,Polestar,cat_zuelpich,21.0,96,75.0,SLOWER than predicted,583,t_arrived: 21d → 96d
33,Peugeot,mosolf_kippenheim,21.0,50,29.0,SLOWER than predicted,1395,t_arrived: 21d → 50d
15,Hyundai,mosolf_cuxhaven,21.0,59,38.0,SLOWER than predicted,997,t_arrived: 21d → 59d
26,Mazda,cat_zuelpich,28.0,50,22.0,SLOWER than predicted,1315,t_arrived: 28d → 50d
21,Kia,blg_saalanderdonau,21.0,68,47.0,SLOWER than predicted,589,t_arrived: 21d → 68d
17,Jeep,mosolf_etzin,21.0,80,59.0,SLOWER than predicted,442,t_arrived: 21d → 80d
3,BYD,mosolf_wilhelmshaven,21.0,29,8.0,SLOWER than predicted,3078,t_arrived: 21d → 29d
20,Kia,blg_bremerhaven,21.0,58,37.0,SLOWER than predicted,610,t_arrived: 21d → 58d
2,BMW,akb_kitzingen,14.0,19,5.0,SLOWER than predicted,4446,t_arrived: 14d → 19d
27,Mercedes-Benz,neuhaus_gmbh_via_bald,14.0,35,21.0,SLOWER than predicted,1037,t_arrived: 14d → 35d
18,Jeep,mosolf_goessnitz,21.0,90,69.0,SLOWER than predicted,270,t_arrived: 21d → 90d
9,Dacia,blg_duisburg,35.0,44,9.0,SLOWER than predicted,2051,t_arrived: 35d → 44d
23,MG,mosolf_wilhelmshaven,21.0,26,5.0,SLOWER than predicted,3610,t_arrived: 21d → 26d

## 10. Lifecycle State Skip Analysis

Some brands routinely skip lifecycle states (e.g., `tech_prep_done` for MG, BYD, BMW/MINI). When a state is skipped, the hardcoded lead time for that phase is meaningless — cars jump directly to the next state, collapsing two phases into one.

This section quantifies **skip rates per brand/compound** to identify where predictions should be adjusted or states removed from the model.

In [17]:
skip_query = f"""
WITH car_states AS (
  SELECT
    car_id,
    MAX(IF(name='car_ordered', JSON_VALUE(snapshot, '$.oem'), NULL)) AS oem,
    MAX(IF(name='car_state_changed_arrived_from_supplier',
           JSON_VALUE(snapshot, '$.infleeting_compound_id'), NULL)) AS compound_id,
    MAX(IF(name='car_ordered', 1, 0)) AS has_ordered,
    MAX(IF(name='car_state_changed_produced', 1, 0)) AS has_produced,
    MAX(IF(name='car_state_changed_arrived_from_supplier', 1, 0)) AS has_arrived,
    MAX(IF(name='car_state_changed_tech_prep_done', 1, 0)) AS has_techprep,
    MAX(IF(name='car_state_changed_ready_to_deliver', 1, 0)) AS has_ready,
    MAX(IF(name='car_state_changed_in_subscription', 1, 0)) AS has_sub
  FROM `datawarehouse-304513.cars_ops_postgres_public.car_events`
  WHERE name IN (
    'car_ordered','car_state_changed_produced','car_state_changed_arrived_from_supplier',
    'car_state_changed_tech_prep_done','car_state_changed_ready_to_deliver',
    'car_state_changed_in_subscription'
  )
  AND time >= '2025-01-01' AND time < '2026-01-01'
  GROUP BY car_id
)
SELECT
  oem AS brand,
  compound_id AS compound,
  COUNT(*) AS total_cars,
  SUM(has_ordered) AS with_ordered,
  SUM(has_produced) AS with_produced,
  SUM(has_arrived) AS with_arrived,
  SUM(has_techprep) AS with_techprep,
  SUM(has_ready) AS with_ready,
  SUM(has_sub) AS with_sub,
  -- Skip rates for key transitions
  ROUND(SAFE_DIVIDE(SUM(IF(has_arrived = 1 AND has_techprep = 0 AND has_ready = 1, 1, 0)),
        SUM(IF(has_arrived = 1 AND has_ready = 1, 1, 0))) * 100, 1) AS pct_skip_techprep,
  ROUND(SAFE_DIVIDE(SUM(IF(has_produced = 0 AND has_arrived = 1, 1, 0)),
        SUM(IF(has_arrived = 1, 1, 0))) * 100, 1) AS pct_skip_produced,
  ROUND(SAFE_DIVIDE(SUM(IF(has_ordered = 1 AND has_produced = 0 AND has_arrived = 1, 1, 0)),
        SUM(IF(has_ordered = 1 AND has_arrived = 1, 1, 0))) * 100, 1) AS pct_ordered_skip_produced
FROM car_states
WHERE (oem, compound_id) IN ({filter_tuples})
GROUP BY 1, 2
HAVING total_cars >= 5
ORDER BY pct_skip_techprep DESC
"""

skip_df = run_query(skip_query)

# Highlight problematic skip rates
high_skip_tp = skip_df[skip_df['pct_skip_techprep'] > 20].copy()
print(f'Brand/compound combos with >20% tech_prep skip rate: {len(high_skip_tp)}')
print()

fig = px.bar(
    skip_df.sort_values('pct_skip_techprep', ascending=True),
    x='pct_skip_techprep',
    y=skip_df.sort_values('pct_skip_techprep', ascending=True).apply(
        lambda r: f"{r['brand']} @ {r['compound']}", axis=1),
    orientation='h',
    title='Tech Prep Done Skip Rate by Brand/Compound (2025)',
    labels={'pct_skip_techprep': '% Cars Skipping Tech Prep', 'y': ''},
    text='pct_skip_techprep',
)
fig.update_layout(
    height=max(500, len(skip_df) * 20), width=900,
    xaxis=dict(range=[0, 100]),
)
fig.show()

print('\nSkip rates summary:')
skip_df[['brand', 'compound', 'total_cars', 'pct_skip_techprep', 'pct_skip_produced', 'pct_ordered_skip_produced']]

Brand/compound combos with >20% tech_prep skip rate: 0

/Users/jan.heiselbetz/venvs/jupyter-py313/lib/python3.13/site-packages/google/cloud/bigquery/table.py:1994: UserWarning:

BigQuery Storage module not found, fetch data with the REST endpoint instead.

Skip rates summary:

,brand,compound,total_cars,pct_skip_techprep,pct_skip_produced,pct_ordered_skip_produced
0,Opel,mosolf_etzin,2273,2.4,0.0,0.0
1,BMW,akb_kitzingen,1971,0.0,0.0,0.0
2,BYD,mosolf_wilhelmshaven,2885,0.0,0.9,0.9
3,Nissan,blg_neuss,593,0.0,0.0,0.0
4,Cupra,akb_zoerbig,1514,0.0,0.0,0.0
5,MG,carserviceerkens_wachtendonk,2903,0.0,0.0,0.0
6,Hyundai,mosolf_rackwitz,1950,0.0,0.0,0.0
7,Hyundai,mosolf_cuxhaven,766,0.0,0.0,0.0
8,Renault,blg_duisburg,540,0.0,0.0,0.0
9,Honda,akb_kitzingen,150,0.0,0.0,0.0
10,Jeep,mosolf_goessnitz,270,0.0,0.0,0.0
11,Peugeot,mosolf_kippenheim,1391,0.0,0.0,0.0
12,Citroen,mosolf_kippenheim,671,0.0,0.0,0.0
13,Seat,akb_zoerbig,366,0.0,0.0,0.0
14,Polestar,cat_zuelpich,478,0.0,0.0,0.0
15,Cadillac,ceva_grevenbroich,13,0.0,0.0,0.0
16,Kia,blg_saalanderdonau,315,0.0,0.0,0.0
17,Opel,mosolf_kippenheim,481,0.0,0.0,0.0
18,Mazda,cat_zuelpich,1050,0.0,0.1,0.1
19,Mercedes-Benz,neuhaus_gmbh_via_bald,695,0.0,0.0,0.0
20,Skoda,mosolf_rackwitz,1192,0.0,0.0,0.0
21,Kia,blg_bremerhaven,374,0.0,0.0,0.0
22,Toyota,blg_saalanderdonau,2141,0.0,0.0,0.0
23,Mazda,blg_duisburg,19,0.0,0.0,0.0
24,MG,mosolf_wilhelmshaven,2026,0.0,0.0,0.0
25,Peugeot,mosolf_etzin,235,0.0,0.0,0.0
26,Ford,cat_zuelpich,399,0.0,0.0,0.0
27,Hyundai,blg_bremerhaven,2472,0.0,0.0,0.0
28,MINI,akb_kitzingen,139,0.0,0.0,0.0
29,DS,mosolf_kippenheim,150,0.0,0.0,0.0
30,Dacia,blg_duisburg,1799,0.0,0.0,0.0
31,Cadillac,ceva_bad_salzungen,11,0.0,0.0,0.0

## 11. Distribution Analysis — Percentile Windows per Phase

Median alone hides the spread. To build calibrated windows that hit 95-99% accuracy, we need the full distribution: P5, P25, P50, P75, P95, P99.

This reveals:
- **Tight distributions** (P5 ≈ P95): predictable, safe to use median
- **Wide distributions** (P95 >> P50): high variance, need wider windows or noise filtering
- **Heavy right tails** (P99 >> P95): outliers from financing blockers, call-off delays, etc.

In [18]:
pctl_query = f"""
WITH events_all AS (
  SELECT
    e.car_id, e.name, e.time,
    JSON_VALUE(e.snapshot, '$.oem') AS oem,
    JSON_VALUE(e.snapshot, '$.infleeting_compound_id') AS compound_id
  FROM `datawarehouse-304513.cars_ops_postgres_public.car_events` e
  WHERE e.name IN (
    'car_ordered','car_state_changed_produced','car_state_changed_arrived_from_supplier',
    'car_state_changed_tech_prep_done','car_state_changed_ready_to_deliver','car_state_changed_in_subscription'
  )
),
cars_active_2025 AS (
  SELECT DISTINCT car_id FROM events_all
  WHERE time >= '2025-01-01' AND time < '2026-01-01'
),
filtered AS (
  SELECT e.* FROM events_all e
  INNER JOIN cars_active_2025 c ON e.car_id = c.car_id
),
state_changes AS (
  SELECT car_id, name, time, oem, compound_id,
    LAG(time) OVER (PARTITION BY car_id ORDER BY time) AS prev_time
  FROM filtered
),
with_days AS (
  SELECT *, DATE_DIFF(DATE(time), DATE(prev_time), DAY) AS days_in_status
  FROM state_changes WHERE prev_time IS NOT NULL
),
compound_lookup AS (
  SELECT DISTINCT car_id, compound_id FROM filtered
  WHERE name = 'car_state_changed_arrived_from_supplier' AND compound_id IS NOT NULL
),
enriched AS (
  SELECT
    d.car_id, d.name, d.days_in_status, d.oem AS brand,
    COALESCE(cl.compound_id, d.compound_id) AS compound
  FROM with_days d
  LEFT JOIN compound_lookup cl ON d.car_id = cl.car_id
  WHERE (d.oem, COALESCE(cl.compound_id, d.compound_id)) IN ({filter_tuples})
)
SELECT
  brand, compound,
  CASE name
    WHEN 'car_state_changed_produced' THEN 'Ordered→Produced'
    WHEN 'car_state_changed_arrived_from_supplier' THEN 'Produced→Arrived'
    WHEN 'car_state_changed_tech_prep_done' THEN 'Arrived→Tech Prep'
    WHEN 'car_state_changed_ready_to_deliver' THEN 'Tech Prep→Ready'
    WHEN 'car_state_changed_in_subscription' THEN 'Ready→Subscription'
  END AS phase,
  COUNT(*) AS n,
  APPROX_QUANTILES(days_in_status, 100 IGNORE NULLS)[OFFSET(5)] AS p5,
  APPROX_QUANTILES(days_in_status, 100 IGNORE NULLS)[OFFSET(25)] AS p25,
  APPROX_QUANTILES(days_in_status, 100 IGNORE NULLS)[OFFSET(50)] AS p50,
  APPROX_QUANTILES(days_in_status, 100 IGNORE NULLS)[OFFSET(75)] AS p75,
  APPROX_QUANTILES(days_in_status, 100 IGNORE NULLS)[OFFSET(95)] AS p95,
  APPROX_QUANTILES(days_in_status, 100 IGNORE NULLS)[OFFSET(99)] AS p99
FROM enriched
WHERE days_in_status >= 0
GROUP BY 1, 2, 3
HAVING n >= 5
ORDER BY brand, compound, phase
"""

pctl_df = run_query(pctl_query)
print(f'{len(pctl_df)} brand/compound/phase rows with percentile data')

# Flag wide distributions (P95/P50 > 3x = heavy tail)
pctl_df['spread_ratio'] = (pctl_df['p95'] / pctl_df['p50'].replace(0, 1)).round(1)
pctl_df['tail_ratio'] = (pctl_df['p99'] / pctl_df['p95'].replace(0, 1)).round(1)
pctl_df['window_95'] = pctl_df['p95'] - pctl_df['p5']  # 90% confidence window width

wide_dist = pctl_df[pctl_df['spread_ratio'] > 3].sort_values('spread_ratio', ascending=False)
print(f'\nPhases with P95/P50 > 3x (unpredictable): {len(wide_dist)}')
if len(wide_dist) > 0:
    print(wide_dist[['brand', 'compound', 'phase', 'n', 'p5', 'p50', 'p95', 'p99', 'spread_ratio']].head(20).to_string(index=False))

# Visualize distribution widths
pctl_df['label'] = pctl_df['brand'] + ' @ ' + pctl_df['compound']
pctl_df

204 brand/compound/phase rows with percentile data

Phases with P95/P50 > 3x (unpredictable): 128
     brand                     compound             phase    n  p5  p50  p95  p99  spread_ratio
    Nissan                    blg_neuss  Ordered→Produced 1228   0    1  151  151         151.0
   Hyundai              blg_bremerhaven  Ordered→Produced 2853   0    0  149  199         149.0
      Fiat            mosolf_kippenheim  Produced→Arrived   46   0    0  138  312         138.0
       BYD         mosolf_wilhelmshaven  Ordered→Produced 3053   0    0  117  117         117.0
Alfa Romeo            mosolf_kippenheim  Produced→Arrived  268   0    0   75   75          75.0
   Hyundai              mosolf_cuxhaven  Ordered→Produced  997   0    2  146  168          73.0
  Cadillac           ceva_bad_salzungen Arrived→Tech Prep   14   0    0   71   71          71.0
     Dacia                 blg_duisburg  Ordered→Produced 2051   0    0   71   83          71.0
  Cadillac            ceva_grevenbroich Arrived→Tech Prep   15   0    0   62   62          62.0
   Citroen            mosolf_kippenheim  Produced→Arrived  769   0    1   56   70          56.0
        MG carserviceerkens_wachtendonk Arrived→Tech Prep 3052   0    0   56  103          56.0
        MG         mosolf_wilhelmshaven Arrived→Tech Prep 2973   0    0   49   55          49.0
Alfa Romeo            mosolf_kippenheim Arrived→Tech Prep  268   0    2   83   83          41.5
      Fiat            mosolf_kippenheim Arrived→Tech Prep   49   0    0   41   44          41.0
     Cupra                  akb_zoerbig Arrived→Tech Prep 1623   0    0   39   79          39.0
       Kia              blg_bremerhaven  Ordered→Produced  610   0    0   36  100          36.0
       Kia           blg_saalanderdonau  Ordered→Produced  589   0    0   36   37          36.0
       BMW                akb_kitzingen Arrived→Tech Prep 3227   0    2   69  125          34.5
       BYD         mosolf_wilhelmshaven   Tech Prep→Ready 3079   0    0   34   55          34.0
  Polestar                 cat_zuelpich   Tech Prep→Ready  415   0    5  162  183          32.4

/Users/jan.heiselbetz/venvs/jupyter-py313/lib/python3.13/site-packages/google/cloud/bigquery/table.py:1994: UserWarning:

BigQuery Storage module not found, fetch data with the REST endpoint instead.

,brand,compound,phase,n,p5,p25,p50,p75,p95,p99,spread_ratio,tail_ratio,window_95,label
0,Alfa Romeo,mosolf_kippenheim,Arrived→Tech Prep,268,0,0,2,26,83,83,41.5,1.0,83,Alfa Romeo @ mosolf_kippenheim
1,Alfa Romeo,mosolf_kippenheim,Ordered→Produced,268,50,113,188,245,366,387,1.9,1.1,316,Alfa Romeo @ mosolf_kippenheim
2,Alfa Romeo,mosolf_kippenheim,Produced→Arrived,268,0,0,0,14,75,75,75.0,1.0,75,Alfa Romeo @ mosolf_kippenheim
3,Alfa Romeo,mosolf_kippenheim,Ready→Subscription,318,7,11,18,34,84,163,4.7,1.9,77,Alfa Romeo @ mosolf_kippenheim
4,Alfa Romeo,mosolf_kippenheim,Tech Prep→Ready,325,1,8,32,74,281,372,8.8,1.3,280,Alfa Romeo @ mosolf_kippenheim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,Toyota,blg_saalanderdonau,Arrived→Tech Prep,3120,0,1,16,31,63,90,3.9,1.4,63,Toyota @ blg_saalanderdonau
200,Toyota,blg_saalanderdonau,Ordered→Produced,3264,0,17,54,110,145,189,2.7,1.3,145,Toyota @ blg_saalanderdonau
201,Toyota,blg_saalanderdonau,Produced→Arrived,2938,1,6,17,51,80,102,4.7,1.3,79,Toyota @ blg_saalanderdonau
202,Toyota,blg_saalanderdonau,Ready→Subscription,2583,6,7,9,15,38,130,4.2,3.4,32,Toyota @ blg_saalanderdonau
203,Toyota,blg_saalanderdonau,Tech Prep→Ready,2785,0,9,31,59,124,466,4.0,3.8,124,Toyota @ blg_saalanderdonau

In [19]:
# Box-plot style visualization: P5-P95 range with P50 marker per phase
# Focus on compound phases (arrived onwards) where predictions matter most

compound_phases = ['Arrived→Tech Prep', 'Tech Prep→Ready', 'Ready→Subscription']
compound_pctl = pctl_df[pctl_df['phase'].isin(compound_phases)].copy()

fig = go.Figure()
for _, row in compound_pctl.sort_values(['phase', 'label']).iterrows():
    fig.add_trace(go.Box(
        name=f"{row['label']} | {row['phase']}",
        lowerfence=[row['p5']],
        q1=[row['p25']],
        median=[row['p50']],
        q3=[row['p75']],
        upperfence=[row['p95']],
        orientation='h',
    ))

fig.update_layout(
    title='Compound Phase Distributions — P5 to P95 Range (2025)',
    xaxis_title='Days',
    height=max(600, len(compound_pctl) * 25),
    width=1000,
    showlegend=False,
)
fig.show()

# Summary: which brand/compound combos have the tightest vs widest windows?
print('=== Tightest 90% windows (most predictable) ===')
tight = pctl_df[pctl_df['phase'].isin(compound_phases)].nsmallest(10, 'window_95')
print(tight[['brand', 'compound', 'phase', 'n', 'p5', 'p50', 'p95', 'window_95']].to_string(index=False))

print('\n=== Widest 90% windows (least predictable) ===')
wide = pctl_df[pctl_df['phase'].isin(compound_phases)].nlargest(10, 'window_95')
print(wide[['brand', 'compound', 'phase', 'n', 'p5', 'p50', 'p95', 'window_95']].to_string(index=False))

=== Tightest 90% windows (most predictable) ===
   brand          compound              phase    n  p5  p50  p95  window_95
   Honda     akb_kitzingen  Arrived→Tech Prep  251   0    0    4          4
Cadillac ceva_grevenbroich Ready→Subscription   13   2    7   13         11
 Citroen mosolf_kippenheim  Arrived→Tech Prep  768   0    5   18         18
    MINI     akb_kitzingen Ready→Subscription  298   2    6   20         18
 Renault      blg_duisburg    Tech Prep→Ready  544   1   12   20         19
    MINI     akb_kitzingen  Arrived→Tech Prep  326   0    0   20         20
 Renault      blg_duisburg  Arrived→Tech Prep  541   6   23   30         24
   Honda     akb_kitzingen Ready→Subscription  170   5    9   30         25
  Nissan         blg_neuss  Arrived→Tech Prep 1238   1    8   26         25
    Opel mosolf_kippenheim  Arrived→Tech Prep  490   0    5   26         26

=== Widest 90% windows (least predictable) ===
     brand                     compound              phase    n  p5  p50  p95  window_95
      Fiat            mosolf_kippenheim    Tech Prep→Ready   91   0   32  452        452
   Peugeot              siebrecht_uslar    Tech Prep→Ready  148   0   38  392        392
      Fiat                 mosolf_etzin    Tech Prep→Ready  266   2   21  386        384
      Opel              siebrecht_uslar    Tech Prep→Ready  631   1   20  375        374
Alfa Romeo            mosolf_kippenheim    Tech Prep→Ready  325   1   32  281        280
      Jeep            mosolf_kippenheim    Tech Prep→Ready  922   1   78  276        275
      Jeep                 mosolf_etzin    Tech Prep→Ready  625   0   33  255        255
      Fiat            mosolf_kippenheim Ready→Subscription   75   7   85  246        239
        MG carserviceerkens_wachtendonk Ready→Subscription 4120   6   27  245        239
      Opel              siebrecht_uslar Ready→Subscription  621   7   27  219        212

## 12. Granularity Comparison — Brand-Level vs. Brand+Compound-Level

Current predictions use Brand+Compound+State granularity. But is compound-level granularity actually needed, or would brand-level be sufficient?

This compares prediction accuracy at two levels:
1. **Brand-level**: same expected lead time for all compounds of a brand
2. **Brand+Compound-level**: different expected lead times per compound (current approach)

If brand+compound produces significantly better accuracy, the granularity is justified.

In [20]:
# Compare brand-level vs brand+compound-level prediction accuracy
# Brand-level: use the brand's average median across all compounds as the "expected"

phase_cols_med = [
    'med_ordered_to_produced', 'med_produced_to_arrived',
    'med_arrived_to_techprep', 'med_techprep_to_ready', 'med_ready_to_sub'
]

# Compute brand-level medians (average of compound medians, weighted by cars)
brand_medians = df.groupby('brand').apply(
    lambda g: pd.Series({
        col: (g[col] * g['cars']).sum() / g['cars'].sum()
        for col in phase_cols_med
    })
).reset_index()

# For each brand/compound, compute error vs brand-level prediction
brand_level_errors = []
compound_level_errors = []

for _, row in comparison.iterrows():
    if pd.isna(row.get('exp_ordered_to_produced')):
        continue
    brand = row['brand']
    brand_med = brand_medians[brand_medians['brand'] == brand]
    if len(brand_med) == 0:
        continue
    brand_med = brand_med.iloc[0]
    
    for actual_col, expected_col, phase_name in phase_mappings:
        actual = row[actual_col]
        expected_compound = row[expected_col]
        expected_brand = brand_med[actual_col]
        
        if pd.notna(actual) and pd.notna(expected_compound) and expected_compound > 0:
            compound_level_errors.append({
                'brand': brand,
                'compound': row['compound'],
                'phase': phase_name,
                'actual': actual,
                'expected': expected_compound,
                'error': abs(actual - expected_compound),
                'level': 'Brand+Compound',
            })
        if pd.notna(actual) and pd.notna(expected_brand) and expected_brand > 0:
            brand_level_errors.append({
                'brand': brand,
                'compound': row['compound'],
                'phase': phase_name,
                'actual': actual,
                'expected': expected_brand,
                'error': abs(actual - expected_brand),
                'level': 'Brand Only',
            })

compound_err_df = pd.DataFrame(compound_level_errors)
brand_err_df = pd.DataFrame(brand_level_errors)

# Compare MAE
print('=== Granularity Comparison: Mean Absolute Error ===\n')
print(f'Brand+Compound level MAE: {compound_err_df["error"].mean():.1f} days')
print(f'Brand-only level MAE:     {brand_err_df["error"].mean():.1f} days')
print(f'Improvement from compound granularity: {brand_err_df["error"].mean() - compound_err_df["error"].mean():.1f} days')

# Compare by phase
print('\n--- MAE by Phase ---')
for phase in ['Ordered→Produced', 'Produced→Arrived', 'Arrived→Tech Prep', 'Tech Prep→Ready', 'Ready→Subscription']:
    c_mae = compound_err_df[compound_err_df['phase'] == phase]['error'].mean()
    b_mae = brand_err_df[brand_err_df['phase'] == phase]['error'].mean()
    better = 'Compound' if c_mae < b_mae else 'Brand'
    print(f'  {phase:25s}  Compound: {c_mae:5.1f}d  Brand: {b_mae:5.1f}d  → {better} wins by {abs(c_mae-b_mae):.1f}d')

# Which brands benefit most from compound granularity?
print('\n--- Brands where compound granularity matters most ---')
both = pd.merge(
    compound_err_df.groupby('brand')['error'].mean().rename('compound_mae'),
    brand_err_df.groupby('brand')['error'].mean().rename('brand_mae'),
    left_index=True, right_index=True
)
both['improvement'] = both['brand_mae'] - both['compound_mae']
both = both.sort_values('improvement', ascending=False)
print(both.round(1).to_string())

=== Granularity Comparison: Mean Absolute Error ===

Brand+Compound level MAE: 13.6 days
Brand-only level MAE:     7.1 days
Improvement from compound granularity: -6.5 days

--- MAE by Phase ---
  Ordered→Produced           Compound:  13.7d  Brand:  23.0d  → Compound wins by 9.3d
  Produced→Arrived           Compound:  17.7d  Brand:   3.7d  → Brand wins by 14.0d
  Arrived→Tech Prep          Compound:   7.8d  Brand:   2.1d  → Brand wins by 5.7d
  Tech Prep→Ready            Compound:  19.1d  Brand:   4.5d  → Brand wins by 14.6d
  Ready→Subscription         Compound:  12.1d  Brand:   4.1d  → Brand wins by 8.0d

--- Brands where compound granularity matters most ---
               compound_mae  brand_mae  improvement
brand
Fiat                   20.7       33.2         12.5
Peugeot                13.6       17.1          3.5
Dacia                   0.0        0.0          0.0
MG                      8.6        6.8         -1.8
Renault                 2.0        0.0         -2.0
Jeep                   26.8       23.8         -3.0
Opel                    9.3        5.5         -3.8
Cadillac               11.2        7.3         -3.9
Hyundai                11.7        6.7         -5.0
Citroen                 6.3        0.0         -6.3
Skoda                   7.5        0.0         -7.5
Mercedes-Benz           9.0        0.0         -9.0
Kia                    12.7        3.1         -9.6
Seat                    9.8        0.0         -9.8
Cupra                   9.8        0.0         -9.8
Toyota                 11.0        0.0        -11.0
MINI                   11.8        0.0        -11.8
Ford                   13.5        0.0        -13.5
DS                     13.7        0.0        -13.7
BYD                    13.7        0.0        -13.7
Nissan                 14.2        0.0        -14.2
BMW                    15.8        0.0        -15.8
Alfa Romeo             16.3        0.0        -16.3
Audi                   16.8        0.0        -16.8
Polestar               22.0        0.0        -22.0
Mazda                  26.5        4.1        -22.4
Honda                  23.2        0.0        -23.2

/var/folders/b7/bv1g5g0x1wz5cw6rkjcwgz7w0000gp/T/ipykernel_54473/2985259448.py:10: FutureWarning:

DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.

## 13. Data-Driven Lead Times & Calibrated Windows

Replace static hardcoded values with **data-driven lead times** and **calibrated deviation windows** that target 95% accuracy.

For each brand/compound/phase:
- **Point estimate**: P50 (median) — best single guess
- **Optimistic bound**: P25 — "if things go well"
- **Conservative bound**: P75 — "realistic buffer"
- **95% window**: [P5, P95] — should capture 90% of cars
- **99% window**: [P1, P99] — should capture 98% of cars

This produces a ready-to-use replacement table for the current static lead times.

In [21]:
# Build the replacement table: data-driven lead times with calibrated windows
# Merge percentile data with current expected values for comparison

phase_order = ['Ordered→Produced', 'Produced→Arrived', 'Arrived→Tech Prep', 'Tech Prep→Ready', 'Ready→Subscription']
exp_col_map = {
    'Ordered→Produced': 'exp_ordered_to_produced',
    'Produced→Arrived': 'exp_produced_to_arrived',
    'Arrived→Tech Prep': 'exp_arrived_to_techprep',
    'Tech Prep→Ready': 'exp_techprep_to_ready',
    'Ready→Subscription': 'exp_ready_to_sub',
}

# Merge expected values into percentile df
calibrated_rows = []
for _, prow in pctl_df.iterrows():
    brand, compound, phase = prow['brand'], prow['compound'], prow['phase']
    exp_row = expected_df[(expected_df['brand'] == brand) & (expected_df['compound'] == compound)]
    
    current_expected = None
    if len(exp_row) > 0 and phase in exp_col_map:
        current_expected = exp_row.iloc[0].get(exp_col_map[phase])
    
    # Check skip rate for this brand/compound
    skip_row = skip_df[(skip_df['brand'] == brand) & (skip_df['compound'] == compound)] if 'skip_df' in dir() else pd.DataFrame()
    skip_pct = skip_row.iloc[0]['pct_skip_techprep'] if len(skip_row) > 0 else None
    
    calibrated_rows.append({
        'brand': brand,
        'compound': compound,
        'phase': phase,
        'n': prow['n'],
        'current_expected': current_expected,
        'p5': prow['p5'],
        'p25': prow['p25'],
        'p50_recommended': prow['p50'],
        'p75': prow['p75'],
        'p95': prow['p95'],
        'p99': prow['p99'],
        'window_90pct': f"[{prow['p5']}–{prow['p95']}]",
        'delta_vs_current': prow['p50'] - current_expected if pd.notna(current_expected) else None,
        'skip_techprep_pct': skip_pct if phase in ['Arrived→Tech Prep', 'Tech Prep→Ready'] else None,
    })

calibrated_df = pd.DataFrame(calibrated_rows)

# Show the replacement table
print('=== Data-Driven Lead Times — Replacement Table ===\n')
print('current_expected = t-minus derived phase duration')
print('p50_recommended = historical median (recommended replacement)')
print('window_90pct = [P5, P95] range capturing 90% of cars\n')

# Focus on compound phases where predictions matter
compound_cal = calibrated_df[calibrated_df['phase'].isin(compound_phases)].copy()
compound_cal = compound_cal.sort_values(['brand', 'compound', 'phase'])
compound_cal[['brand', 'compound', 'phase', 'n', 'current_expected', 'p50_recommended', 
              'delta_vs_current', 'window_90pct', 'skip_techprep_pct']]

=== Data-Driven Lead Times — Replacement Table ===

current_expected = t-minus derived phase duration
p50_recommended = historical median (recommended replacement)
window_90pct = [P5, P95] range capturing 90% of cars

,brand,compound,phase,n,current_expected,p50_recommended,delta_vs_current,window_90pct,skip_techprep_pct
0,Alfa Romeo,mosolf_kippenheim,Arrived→Tech Prep,268,11.0,2,-9.0,[0–83],NaN
3,Alfa Romeo,mosolf_kippenheim,Ready→Subscription,318,9.0,18,9.0,[7–84],NaN
4,Alfa Romeo,mosolf_kippenheim,Tech Prep→Ready,325,1.0,32,31.0,[1–281],NaN
5,Audi,akb_kitzingen,Arrived→Tech Prep,2483,14.0,20,6.0,[0–73],NaN
8,Audi,akb_kitzingen,Ready→Subscription,2543,7.0,8,1.0,[3–35],NaN
...,...,...,...,...,...,...,...,...,...
197,Skoda,mosolf_rackwitz,Ready→Subscription,1937,5.0,10,5.0,[6–41],NaN
198,Skoda,mosolf_rackwitz,Tech Prep→Ready,2208,23.0,7,-16.0,[1–29],0.0
199,Toyota,blg_saalanderdonau,Arrived→Tech Prep,3120,11.0,16,5.0,[0–63],0.0
202,Toyota,blg_saalanderdonau,Ready→Subscription,2583,7.0,9,2.0,[6–38],NaN
203,Toyota,blg_saalanderdonau,Tech Prep→Ready,2785,3.0,31,28.0,[0–124],0.0

In [22]:
# Visualize: current expected vs data-driven P50 with P5-P95 error bars
# For compound phases only

for phase in compound_phases:
    phase_data = calibrated_df[
        (calibrated_df['phase'] == phase) & 
        calibrated_df['current_expected'].notna()
    ].sort_values('p50_recommended')
    
    if len(phase_data) == 0:
        continue
    
    labels = phase_data.apply(lambda r: f"{r['brand']} @ {r['compound']}", axis=1)
    
    fig = go.Figure()
    
    # P5-P95 range (error bars)
    fig.add_trace(go.Scatter(
        x=phase_data['p50_recommended'],
        y=labels,
        error_x=dict(
            type='data',
            symmetric=False,
            array=phase_data['p95'] - phase_data['p50_recommended'],
            arrayminus=phase_data['p50_recommended'] - phase_data['p5'],
        ),
        mode='markers',
        marker=dict(size=10, color='#4e79a7'),
        name='Data-Driven P50 [P5–P95]',
    ))
    
    # Current expected (red markers)
    fig.add_trace(go.Scatter(
        x=phase_data['current_expected'],
        y=labels,
        mode='markers',
        marker=dict(size=10, symbol='x', color='red'),
        name='Current Hardcoded',
    ))
    
    fig.update_layout(
        title=f'{phase}: Current vs Data-Driven Lead Times',
        xaxis_title='Days',
        height=max(400, len(phase_data) * 25),
        width=900,
        legend=dict(orientation='h', yanchor='bottom', y=1.02),
    )
    fig.show()

### 13.1 Summary: Key Findings & Recommendations

**Interpretation guide for the replacement table above:**
- `delta_vs_current > 0`: current prediction is too optimistic (cars take longer)
- `delta_vs_current < 0`: current prediction is too pessimistic (cars arrive faster)
- `skip_techprep_pct > 50%`: this brand regularly skips tech_prep — consider removing it from the model
- `window_90pct` width > 20 days: high variance, single point estimate is unreliable

In [23]:
# Final summary: actionable recommendations
print('=' * 80)
print('ACTIONABLE RECOMMENDATIONS')
print('=' * 80)

# 1. Phases to update
print('\n1. LEAD TIMES TO UPDATE (current off by >3 days, compound phases only):')
updates = calibrated_df[
    (calibrated_df['phase'].isin(compound_phases)) &
    (calibrated_df['delta_vs_current'].notna()) &
    (calibrated_df['delta_vs_current'].abs() > 3)
].sort_values('delta_vs_current', key=abs, ascending=False)

if len(updates) > 0:
    for _, r in updates.iterrows():
        direction = 'TOO LOW' if r['delta_vs_current'] > 0 else 'TOO HIGH'
        print(f"  {r['brand']:15s} @ {r['compound']:30s} | {r['phase']:20s} | "
              f"current: {r['current_expected']:4.0f}d → recommended: {r['p50_recommended']:4.0f}d "
              f"({direction}, off by {abs(r['delta_vs_current']):.0f}d) "
              f"[P5-P95: {r['p5']}-{r['p95']}d, n={r['n']}]")

# 2. States to skip
print('\n2. LIFECYCLE STATES TO CONSIDER REMOVING (>50% skip rate):')
if 'skip_df' in dir():
    high_skip = skip_df[skip_df['pct_skip_techprep'] > 50]
    for _, r in high_skip.iterrows():
        print(f"  {r['brand']:15s} @ {r['compound']:30s} | tech_prep skip rate: {r['pct_skip_techprep']:.0f}% ({r['total_cars']} cars)")

# 3. High-variance phases (unreliable single-point predictions)
print('\n3. HIGH-VARIANCE PHASES (90% window > 30 days — need dynamic windows):')
high_var = calibrated_df[
    (calibrated_df['phase'].isin(compound_phases)) &
    ((calibrated_df['p95'] - calibrated_df['p5']) > 30)
].sort_values('p95', ascending=False)
for _, r in high_var.iterrows():
    print(f"  {r['brand']:15s} @ {r['compound']:30s} | {r['phase']:20s} | "
          f"P50: {r['p50_recommended']:.0f}d, but 90% window: [{r['p5']:.0f}–{r['p95']:.0f}]d (spread: {r['p95']-r['p5']:.0f}d, n={r['n']})")

# 4. Fleet vs Infleeting ownership summary
print('\n4. FLEET vs INFLEETING OWNERSHIP SUMMARY:')
print('   Fleet-owned (ordered→arrived): ETA accuracy — no prediction data in car_events to compare')
print('   Infleeting-owned (arrived→subscription): compound lead time accuracy — directly testable\n')

# Show which brands have Fleet-dominated vs Infleeting-dominated error
for _, exp_r in expected_df[expected_df['t_arrived'].notna()].iterrows():
    brand, compound = exp_r['brand'], exp_r['compound']
    actual_row = df[(df['brand'] == brand) & (df['compound'] == compound)]
    if len(actual_row) == 0:
        continue
    ar = actual_row.iloc[0]
    fleet_actual = (ar.get('med_ordered_to_produced', 0) or 0) + (ar.get('med_produced_to_arrived', 0) or 0)
    infleeting_actual = (ar.get('med_arrived_to_techprep', 0) or 0) + (ar.get('med_techprep_to_ready', 0) or 0) + (ar.get('med_ready_to_sub', 0) or 0)
    infleeting_predicted = exp_r['t_arrived']
    infleeting_error = infleeting_actual - infleeting_predicted
    total = fleet_actual + infleeting_actual
    fleet_pct = (fleet_actual / total * 100) if total > 0 else 0
    if fleet_pct > 70 or abs(infleeting_error) > 10:
        owner = 'FLEET' if fleet_pct > 70 else 'INFLEETING'
        print(f"  {brand:15s} @ {compound:30s} | Fleet: {fleet_actual:.0f}d ({fleet_pct:.0f}%), Infleeting: {infleeting_actual:.0f}d (predicted {infleeting_predicted:.0f}d, Δ{infleeting_error:+.0f}d) → {owner} dominates"
        )

================================================================================
ACTIONABLE RECOMMENDATIONS
================================================================================

1. LEAD TIMES TO UPDATE (current off by >3 days, compound phases only):
  Polestar        @ cat_zuelpich                   | Arrived→Tech Prep    | current:   14d → recommended:   99d (TOO LOW, off by 85d) [P5-P95: 0-119d, n=408]
  Jeep            @ mosolf_kippenheim              | Tech Prep→Ready      | current:    1d → recommended:   78d (TOO LOW, off by 77d) [P5-P95: 1-276d, n=922]
  Fiat            @ mosolf_kippenheim              | Ready→Subscription   | current:    9d → recommended:   85d (TOO LOW, off by 76d) [P5-P95: 7-246d, n=75]
  Jeep            @ mosolf_goessnitz               | Ready→Subscription   | current:    9d → recommended:   65d (TOO LOW, off by 56d) [P5-P95: 8-127d, n=299]
  Peugeot         @ siebrecht_uslar                | Ready→Subscription   | current:    7d → recommended:   55d (TOO LOW, off by 48d) [P5-P95: 11-138d, n=141]
  Cadillac        @ ceva_grevenbroich              | Tech Prep→Ready      | current:    3d → recommended:   49d (TOO LOW, off by 46d) [P5-P95: 0-112d, n=15]
  Nissan          @ blg_neuss                      | Tech Prep→Ready      | current:    3d → recommended:   43d (TOO LOW, off by 40d) [P5-P95: 6-126d, n=1323]
  Peugeot         @ siebrecht_uslar                | Tech Prep→Ready      | current:    2d → recommended:   38d (TOO LOW, off by 36d) [P5-P95: 0-392d, n=148]
  Mazda           @ cat_zuelpich                   | Arrived→Tech Prep    | current:    0d → recommended:   35d (TOO LOW, off by 35d) [P5-P95: 0-84d, n=1240]
  Kia             @ blg_saalanderdonau             | Tech Prep→Ready      | current:    3d → recommended:   37d (TOO LOW, off by 34d) [P5-P95: 3-125d, n=592]
  Jeep            @ mosolf_etzin                   | Ready→Subscription   | current:    9d → recommended:   43d (TOO LOW, off by 34d) [P5-P95: 9-105d, n=605]
  Jeep            @ mosolf_etzin                   | Tech Prep→Ready      | current:    1d → recommended:   33d (TOO LOW, off by 32d) [P5-P95: 0-255d, n=625]
  Alfa Romeo      @ mosolf_kippenheim              | Tech Prep→Ready      | current:    1d → recommended:   32d (TOO LOW, off by 31d) [P5-P95: 1-281d, n=325]
  Fiat            @ mosolf_kippenheim              | Tech Prep→Ready      | current:    1d → recommended:   32d (TOO LOW, off by 31d) [P5-P95: 0-452d, n=91]
  Kia             @ blg_bremerhaven                | Tech Prep→Ready      | current:    3d → recommended:   32d (TOO LOW, off by 29d) [P5-P95: 3-132d, n=617]
  Toyota          @ blg_saalanderdonau             | Tech Prep→Ready      | current:    3d → recommended:   31d (TOO LOW, off by 28d) [P5-P95: 0-124d, n=2785]
  DS              @ mosolf_kippenheim              | Ready→Subscription   | current:    9d → recommended:   36d (TOO LOW, off by 27d) [P5-P95: 8-97d, n=150]
  DS              @ mosolf_kippenheim              | Tech Prep→Ready      | current:    0d → recommended:   25d (TOO LOW, off by 25d) [P5-P95: 1-30d, n=150]
  Hyundai         @ mosolf_cuxhaven                | Arrived→Tech Prep    | current:   11d → recommended:   36d (TOO LOW, off by 25d) [P5-P95: 0-69d, n=996]
  Mercedes-Benz   @ neuhaus_gmbh_via_bald          | Arrived→Tech Prep    | current:   -7d → recommended:   16d (TOO LOW, off by 23d) [P5-P95: 0-56d, n=782]
  Peugeot         @ mosolf_kippenheim              | Tech Prep→Ready      | current:    0d → recommended:   21d (TOO LOW, off by 21d) [P5-P95: 3-32d, n=1406]
  MG              @ carserviceerkens_wachtendonk   | Ready→Subscription   | current:    7d → recommended:   27d (TOO LOW, off by 20d) [P5-P95: 6-245d, n=4120]
  Opel            @ siebrecht_uslar                | Ready→Subscription   | current:    7d → recommended:   27d (TOO LOW, off by 20d) [P5-P95: 7-219d, n=621]
  Polestar        @ cat_zuelpich                   | Ready→Subscription   | current:    5d → recommended:   25d (TOO LOW, off by 20d) [P5-P95: 3-95d, n=383]
  Mazda           @ cat_zuelpich                   | Ready→Subscription   | current:   28d → recommended:    8d (TOO HIGH, off by 20d) [P5-P95: 3-35d, n=1086]
  Jeep            @ mosolf_kippenheim              | Ready→Subscription   | current:    9d → recommended:   29d (TOO LOW, off by 20d) [P5-P95: 7-149d, n=852]
  Fiat            @ mosolf_etzin                   | Tech Prep→Ready      | current:    1d → recommended:   21d (TOO LOW, off by 20d) [P5-P95: 2-386d, n=266]
  Opel            @ mosolf_etzin                   | Tech Prep→Ready      | current:    0d → recommended:   20d (TOO LOW, off by 20d) [P5-P95: 1-35d, n=2581]
  Opel            @ mosolf_kippenheim              | Tech Prep→Ready      | current:    0d → recommended:   20d (TOO LOW, off by 20d) [P5-P95: 3-35d, n=487]
  Ford            @ cat_zuelpich                   | Tech Prep→Ready      | current:    9d → recommended:   28d (TOO LOW, off by 19d) [P5-P95: 0-99d, n=512]
  Hyundai         @ blg_bremerhaven                | Tech Prep→Ready      | current:    3d → recommended:   21d (TOO LOW, off by 18d) [P5-P95: 1-80d, n=2690]
  Opel            @ siebrecht_uslar                | Tech Prep→Ready      | current:    2d → recommended:   20d (TOO LOW, off by 18d) [P5-P95: 1-375d, n=631]
  Hyundai         @ mosolf_rackwitz                | Tech Prep→Ready      | current:    5d → recommended:   21d (TOO LOW, off by 16d) [P5-P95: 1-77d, n=2220]
  Skoda           @ mosolf_rackwitz                | Tech Prep→Ready      | current:   23d → recommended:    7d (TOO HIGH, off by 16d) [P5-P95: 1-29d, n=2208]
  Honda           @ akb_kitzingen                  | Tech Prep→Ready      | current:    3d → recommended:   19d (TOO LOW, off by 16d) [P5-P95: 1-55d, n=185]
  BYD             @ mosolf_wilhelmshaven           | Ready→Subscription   | current:   14d → recommended:   29d (TOO LOW, off by 15d) [P5-P95: 9-85d, n=2755]
  MG              @ mosolf_wilhelmshaven           | Ready→Subscription   | current:    9d → recommended:   24d (TOO LOW, off by 15d) [P5-P95: 8-107d, n=2298]
  Seat            @ akb_zoerbig                    | Arrived→Tech Prep    | current:    7d → recommended:   22d (TOO LOW, off by 15d) [P5-P95: 0-52d, n=369]
  Cadillac        @ ceva_bad_salzungen             | Tech Prep→Ready      | current:    3d → recommended:   18d (TOO LOW, off by 15d) [P5-P95: 0-86d, n=14]
  Hyundai         @ mosolf_rackwitz                | Arrived→Tech Prep    | current:   11d → recommended:   25d (TOO LOW, off by 14d) [P5-P95: 0-71d, n=2306]
  Peugeot         @ mosolf_etzin                   | Tech Prep→Ready      | current:    0d → recommended:   14d (TOO LOW, off by 14d) [P5-P95: 2-51d, n=318]
  Ford            @ cat_zuelpich                   | Arrived→Tech Prep    | current:    7d → recommended:   20d (TOO LOW, off by 13d) [P5-P95: 0-49d, n=514]
  Citroen         @ mosolf_kippenheim              | Tech Prep→Ready      | current:    0d → recommended:   13d (TOO LOW, off by 13d) [P5-P95: 1-28d, n=777]
  Opel            @ mosolf_etzin                   | Ready→Subscription   | current:    9d → recommended:   22d (TOO LOW, off by 13d) [P5-P95: 7-76d, n=2539]
  Renault         @ blg_duisburg                   | Tech Prep→Ready      | current:    0d → recommended:   12d (TOO LOW, off by 12d) [P5-P95: 1-20d, n=544]
  Jeep            @ mosolf_goessnitz               | Tech Prep→Ready      | current:    1d → recommended:   13d (TOO LOW, off by 12d) [P5-P95: 0-68d, n=314]
  Kia             @ blg_saalanderdonau             | Arrived→Tech Prep    | current:   11d → recommended:   22d (TOO LOW, off by 11d) [P5-P95: 0-57d, n=589]
  Hyundai         @ mosolf_cuxhaven                | Tech Prep→Ready      | current:    3d → recommended:   14d (TOO LOW, off by 11d) [P5-P95: 0-67d, n=988]
  BYD             @ mosolf_wilhelmshaven           | Arrived→Tech Prep    | current:   11d → recommended:    0d (TOO HIGH, off by 11d) [P5-P95: 0-29d, n=3071]
  MG              @ mosolf_wilhelmshaven           | Arrived→Tech Prep    | current:   11d → recommended:    0d (TOO HIGH, off by 11d) [P5-P95: 0-49d, n=2973]
  Fiat            @ mosolf_kippenheim              | Arrived→Tech Prep    | current:   11d → recommended:    0d (TOO HIGH, off by 11d) [P5-P95: 0-41d, n=49]
  Honda           @ akb_kitzingen                  | Arrived→Tech Prep    | current:   11d → recommended:    0d (TOO HIGH, off by 11d) [P5-P95: 0-4d, n=251]
  Peugeot         @ mosolf_kippenheim              | Ready→Subscription   | current:    9d → recommended:   19d (TOO LOW, off by 10d) [P5-P95: 8-69d, n=1399]
  Dacia           @ blg_duisburg                   | Tech Prep→Ready      | current:    0d → recommended:   10d (TOO LOW, off by 10d) [P5-P95: 0-51d, n=2064]
  Fiat            @ mosolf_etzin                   | Ready→Subscription   | current:    9d → recommended:   18d (TOO LOW, off by 9d) [P5-P95: 7-124d, n=266]
  Opel            @ siebrecht_uslar                | Arrived→Tech Prep    | current:   12d → recommended:    3d (TOO HIGH, off by 9d) [P5-P95: 0-43d, n=470]
  Alfa Romeo      @ mosolf_kippenheim              | Ready→Subscription   | current:    9d → recommended:   18d (TOO LOW, off by 9d) [P5-P95: 7-84d, n=318]
  MINI            @ akb_kitzingen                  | Tech Prep→Ready      | current:    3d → recommended:   12d (TOO LOW, off by 9d) [P5-P95: 0-34d, n=323]
  Alfa Romeo      @ mosolf_kippenheim              | Arrived→Tech Prep    | current:   11d → recommended:    2d (TOO HIGH, off by 9d) [P5-P95: 0-83d, n=268]
  Peugeot         @ siebrecht_uslar                | Arrived→Tech Prep    | current:   12d → recommended:    4d (TOO HIGH, off by 8d) [P5-P95: 0-27d, n=97]
  Opel            @ mosolf_kippenheim              | Ready→Subscription   | current:    9d → recommended:   17d (TOO LOW, off by 8d) [P5-P95: 7-47d, n=487]
  Cupra           @ akb_zoerbig                    | Arrived→Tech Prep    | current:    7d → recommended:    0d (TOO HIGH, off by 7d) [P5-P95: 0-39d, n=1623]
  Audi            @ akb_kitzingen                  | Tech Prep→Ready      | current:   14d → recommended:    7d (TOO HIGH, off by 7d) [P5-P95: 0-85d, n=2551]
  Citroen         @ mosolf_kippenheim              | Arrived→Tech Prep    | current:   12d → recommended:    5d (TOO HIGH, off by 7d) [P5-P95: 0-18d, n=768]
  Peugeot         @ mosolf_etzin                   | Ready→Subscription   | current:    9d → recommended:   16d (TOO LOW, off by 7d) [P5-P95: 7-62d, n=285]
  Mazda           @ cat_zuelpich                   | Tech Prep→Ready      | current:    0d → recommended:    7d (TOO LOW, off by 7d) [P5-P95: 0-67d, n=1177]
  DS              @ mosolf_kippenheim              | Arrived→Tech Prep    | current:   12d → recommended:    5d (TOO HIGH, off by 7d) [P5-P95: 0-54d, n=150]
  Opel            @ mosolf_kippenheim              | Arrived→Tech Prep    | current:   12d → recommended:    5d (TOO HIGH, off by 7d) [P5-P95: 0-26d, n=490]
  Jeep            @ mosolf_etzin                   | Arrived→Tech Prep    | current:   11d → recommended:    4d (TOO HIGH, off by 7d) [P5-P95: 0-28d, n=442]
  Citroen         @ mosolf_kippenheim              | Ready→Subscription   | current:    9d → recommended:   15d (TOO LOW, off by 6d) [P5-P95: 7-47d, n=745]
  Audi            @ akb_kitzingen                  | Arrived→Tech Prep    | current:   14d → recommended:   20d (TOO LOW, off by 6d) [P5-P95: 0-73d, n=2483]
  Kia             @ blg_bremerhaven                | Arrived→Tech Prep    | current:   11d → recommended:   17d (TOO LOW, off by 6d) [P5-P95: 0-57d, n=610]
  BMW             @ akb_kitzingen                  | Tech Prep→Ready      | current:    3d → recommended:    9d (TOO LOW, off by 6d) [P5-P95: 0-59d, n=3187]
  Toyota          @ blg_saalanderdonau             | Arrived→Tech Prep    | current:   11d → recommended:   16d (TOO LOW, off by 5d) [P5-P95: 0-63d, n=3120]
  Fiat            @ mosolf_etzin                   | Arrived→Tech Prep    | current:   11d → recommended:    6d (TOO HIGH, off by 5d) [P5-P95: 0-40d, n=227]
  Skoda           @ mosolf_rackwitz                | Ready→Subscription   | current:    5d → recommended:   10d (TOO LOW, off by 5d) [P5-P95: 6-41d, n=1937]
  Skoda           @ mosolf_rackwitz                | Arrived→Tech Prep    | current:    7d → recommended:   12d (TOO LOW, off by 5d) [P5-P95: 0-70d, n=2277]
  BYD             @ mosolf_wilhelmshaven           | Tech Prep→Ready      | current:   -4d → recommended:    0d (TOO LOW, off by 4d) [P5-P95: 0-34d, n=3079]
  MG              @ carserviceerkens_wachtendonk   | Arrived→Tech Prep    | current:    4d → recommended:    0d (TOO HIGH, off by 4d) [P5-P95: 0-56d, n=3052]
  Cadillac        @ ceva_bad_salzungen             | Arrived→Tech Prep    | current:    4d → recommended:    0d (TOO HIGH, off by 4d) [P5-P95: 0-71d, n=14]
  Cadillac        @ ceva_grevenbroich              | Arrived→Tech Prep    | current:    4d → recommended:    0d (TOO HIGH, off by 4d) [P5-P95: 0-62d, n=15]
  Hyundai         @ mosolf_rackwitz                | Ready→Subscription   | current:    5d → recommended:    9d (TOO LOW, off by 4d) [P5-P95: 5-32d, n=2165]
  MINI            @ akb_kitzingen                  | Arrived→Tech Prep    | current:    4d → recommended:    0d (TOO HIGH, off by 4d) [P5-P95: 0-20d, n=326]

2. LIFECYCLE STATES TO CONSIDER REMOVING (>50% skip rate):

3. HIGH-VARIANCE PHASES (90% window > 30 days — need dynamic windows):
  Fiat            @ mosolf_kippenheim              | Tech Prep→Ready      | P50: 32d, but 90% window: [0–452]d (spread: 452d, n=91)
  Peugeot         @ siebrecht_uslar                | Tech Prep→Ready      | P50: 38d, but 90% window: [0–392]d (spread: 392d, n=148)
  Fiat            @ mosolf_etzin                   | Tech Prep→Ready      | P50: 21d, but 90% window: [2–386]d (spread: 384d, n=266)
  Opel            @ siebrecht_uslar                | Tech Prep→Ready      | P50: 20d, but 90% window: [1–375]d (spread: 374d, n=631)
  Alfa Romeo      @ mosolf_kippenheim              | Tech Prep→Ready      | P50: 32d, but 90% window: [1–281]d (spread: 280d, n=325)
  Jeep            @ mosolf_kippenheim              | Tech Prep→Ready      | P50: 78d, but 90% window: [1–276]d (spread: 275d, n=922)
  Jeep            @ mosolf_etzin                   | Tech Prep→Ready      | P50: 33d, but 90% window: [0–255]d (spread: 255d, n=625)
  Fiat            @ mosolf_kippenheim              | Ready→Subscription   | P50: 85d, but 90% window: [7–246]d (spread: 239d, n=75)
  MG              @ carserviceerkens_wachtendonk   | Ready→Subscription   | P50: 27d, but 90% window: [6–245]d (spread: 239d, n=4120)
  Opel            @ siebrecht_uslar                | Ready→Subscription   | P50: 27d, but 90% window: [7–219]d (spread: 212d, n=621)
  Polestar        @ cat_zuelpich                   | Tech Prep→Ready      | P50: 5d, but 90% window: [0–162]d (spread: 162d, n=415)
  Mazda           @ blg_duisburg                   | Arrived→Tech Prep    | P50: 64d, but 90% window: [0–154]d (spread: 154d, n=469)
  Jeep            @ mosolf_kippenheim              | Ready→Subscription   | P50: 29d, but 90% window: [7–149]d (spread: 142d, n=852)
  Peugeot         @ siebrecht_uslar                | Ready→Subscription   | P50: 55d, but 90% window: [11–138]d (spread: 127d, n=141)
  Kia             @ blg_bremerhaven                | Tech Prep→Ready      | P50: 32d, but 90% window: [3–132]d (spread: 129d, n=617)
  Jeep            @ mosolf_goessnitz               | Ready→Subscription   | P50: 65d, but 90% window: [8–127]d (spread: 119d, n=299)
  Nissan          @ blg_neuss                      | Tech Prep→Ready      | P50: 43d, but 90% window: [6–126]d (spread: 120d, n=1323)
  Kia             @ blg_saalanderdonau             | Tech Prep→Ready      | P50: 37d, but 90% window: [3–125]d (spread: 122d, n=592)
  Fiat            @ mosolf_etzin                   | Ready→Subscription   | P50: 18d, but 90% window: [7–124]d (spread: 117d, n=266)
  Toyota          @ blg_saalanderdonau             | Tech Prep→Ready      | P50: 31d, but 90% window: [0–124]d (spread: 124d, n=2785)
  Polestar        @ cat_zuelpich                   | Arrived→Tech Prep    | P50: 99d, but 90% window: [0–119]d (spread: 119d, n=408)
  Cadillac        @ ceva_grevenbroich              | Tech Prep→Ready      | P50: 49d, but 90% window: [0–112]d (spread: 112d, n=15)
  MG              @ mosolf_wilhelmshaven           | Ready→Subscription   | P50: 24d, but 90% window: [8–107]d (spread: 99d, n=2298)
  Jeep            @ mosolf_etzin                   | Ready→Subscription   | P50: 43d, but 90% window: [9–105]d (spread: 96d, n=605)
  Ford            @ cat_zuelpich                   | Tech Prep→Ready      | P50: 28d, but 90% window: [0–99]d (spread: 99d, n=512)
  DS              @ mosolf_kippenheim              | Ready→Subscription   | P50: 36d, but 90% window: [8–97]d (spread: 89d, n=150)
  Polestar        @ cat_zuelpich                   | Ready→Subscription   | P50: 25d, but 90% window: [3–95]d (spread: 92d, n=383)
  Cadillac        @ ceva_bad_salzungen             | Tech Prep→Ready      | P50: 18d, but 90% window: [0–86]d (spread: 86d, n=14)
  BYD             @ mosolf_wilhelmshaven           | Ready→Subscription   | P50: 29d, but 90% window: [9–85]d (spread: 76d, n=2755)
  Audi            @ akb_kitzingen                  | Tech Prep→Ready      | P50: 7d, but 90% window: [0–85]d (spread: 85d, n=2551)
  Alfa Romeo      @ mosolf_kippenheim              | Ready→Subscription   | P50: 18d, but 90% window: [7–84]d (spread: 77d, n=318)
  Mazda           @ cat_zuelpich                   | Arrived→Tech Prep    | P50: 35d, but 90% window: [0–84]d (spread: 84d, n=1240)
  Hyundai         @ blg_bremerhaven                | Arrived→Tech Prep    | P50: 27d, but 90% window: [0–84]d (spread: 84d, n=2758)
  Alfa Romeo      @ mosolf_kippenheim              | Arrived→Tech Prep    | P50: 2d, but 90% window: [0–83]d (spread: 83d, n=268)
  Hyundai         @ blg_bremerhaven                | Tech Prep→Ready      | P50: 21d, but 90% window: [1–80]d (spread: 79d, n=2690)
  Cupra           @ akb_zoerbig                    | Tech Prep→Ready      | P50: 19d, but 90% window: [1–79]d (spread: 78d, n=1601)
  Mazda           @ blg_duisburg                   | Tech Prep→Ready      | P50: 9d, but 90% window: [0–79]d (spread: 79d, n=473)
  Hyundai         @ mosolf_rackwitz                | Tech Prep→Ready      | P50: 21d, but 90% window: [1–77]d (spread: 76d, n=2220)
  Opel            @ mosolf_etzin                   | Ready→Subscription   | P50: 22d, but 90% window: [7–76]d (spread: 69d, n=2539)
  Audi            @ akb_kitzingen                  | Arrived→Tech Prep    | P50: 20d, but 90% window: [0–73]d (spread: 73d, n=2483)
  Cadillac        @ ceva_bad_salzungen             | Arrived→Tech Prep    | P50: 0d, but 90% window: [0–71]d (spread: 71d, n=14)
  Hyundai         @ mosolf_rackwitz                | Arrived→Tech Prep    | P50: 25d, but 90% window: [0–71]d (spread: 71d, n=2306)
  Skoda           @ mosolf_rackwitz                | Arrived→Tech Prep    | P50: 12d, but 90% window: [0–70]d (spread: 70d, n=2277)
  Hyundai         @ mosolf_cuxhaven                | Arrived→Tech Prep    | P50: 36d, but 90% window: [0–69]d (spread: 69d, n=996)
  BMW             @ akb_kitzingen                  | Arrived→Tech Prep    | P50: 2d, but 90% window: [0–69]d (spread: 69d, n=3227)
  Peugeot         @ mosolf_kippenheim              | Ready→Subscription   | P50: 19d, but 90% window: [8–69]d (spread: 61d, n=1399)
  Jeep            @ mosolf_goessnitz               | Tech Prep→Ready      | P50: 13d, but 90% window: [0–68]d (spread: 68d, n=314)
  Mazda           @ cat_zuelpich                   | Tech Prep→Ready      | P50: 7d, but 90% window: [0–67]d (spread: 67d, n=1177)
  Hyundai         @ mosolf_cuxhaven                | Tech Prep→Ready      | P50: 14d, but 90% window: [0–67]d (spread: 67d, n=988)

## 14. Blocker Performance vs Configured Shift Times

**Goal**: Compare actual blocker resolution times against configured criticality thresholds (from `isCritical` in `check-infleeting-blockers.ts`).

- **Red = too slow**: Blockers take longer to resolve than the configured threshold → late delivery risk
- **Blue = too fast**: Blockers resolve faster than expected → threshold may be too generous (unnecessary delay)

Data source: `blockers_events` table — pairing `blocker_created` → `blocker_resolved`/`blocker_deleted` events per car.

#### Configured Criticality Thresholds

These values come from `check-infleeting-blockers.ts` — the `isCritical(blockedDays, handoverDate, N)` calls.
Each blocker becomes **critical** when there are `≤ N` working days until the handover date.

We use these as the benchmark: if a blocker typically takes longer than `N` working days to resolve, the threshold is too short and cars will be delayed.

In [ ]:
# Configured criticality thresholds (working days) from check-infleeting-blockers.ts isCritical() calls
# These represent "blocker becomes critical when <= N working days before handover"
CONFIGURED_SHIFTS_WD = {
    'not_produced': 20,
    'not_yet_at_compound': 10,
    'subscription_missing': 5,
    'pdi_not_done': 10,
    'registration_papers_missing': 10,
    'in_registration': 3,
    'registration_missing': 5,
    'deposit_not_paid': 4,
    'tires_not_mounted': 5,
    'sa_number_missing': 5,
    'turnover_car_in_returned_status': 10,
    'wrong_insurance': 7,
    'car_missing_payment': 10,
    'car_at_wrong_compound': 10,
    'missing_delivery': 3,
    'hu_au_missing': 20,
    # Always-critical blockers (no fixed threshold) — use None
    'pickup_too_soon': None,
    'pickup_date_in_the_past': None,
    'delivery_not_accepted': None,
    'handover_date_in_the_past': None,
    'mismatch_terms_registration': None,
    # Manual blockers — no automated threshold
    'workshop': None,
    'infleeting_workshop': None,
    'damage': None,
    'call_back_from_oem': None,
    'car_location_unclear': None,
    'truck_delivery_blocked': None,
    'invoice_not_paid_by_finn': None,
}

# Only analyze blockers with a numeric threshold
ANALYZABLE_BLOCKERS = {k: v for k, v in CONFIGURED_SHIFTS_WD.items() if v is not None}
print(f"{len(ANALYZABLE_BLOCKERS)} blockers with configured thresholds")
print(f"{len(CONFIGURED_SHIFTS_WD) - len(ANALYZABLE_BLOCKERS)} always-critical / manual blockers (excluded from shift comparison)")

#### Core Query — Blocker Episode Duration

The `blockers_events` table logs individual events: `blocker_created`, `blocker_resolved`, `blocker_deleted`.
A single car can have **multiple episodes** of the same blocker (e.g., PDI not done → resolved → created again).

**Pairing logic**: For each `(car_id, blocking_reason)`, we use `ROW_NUMBER()` to match the 1st `blocker_created` with the 1st `blocker_resolved`/`blocker_deleted`, the 2nd with the 2nd, etc. This gives us the duration of each individual blocker episode.

**Working days approximation**: `calendar_days − 2 × floor(calendar_days / 7)` — subtracts weekends but not holidays. Sufficient for comparative analysis.

**Filters**: 2025 data only, durations 0–365 days (excludes negative/stale), restricted to the 40 brand/compound combos defined above.

In [ ]:
blocker_query = f"""
WITH blocker_pairs AS (
  -- Pair Nth blocker_created with Nth blocker_resolved/blocker_deleted per (car_id, blocking_reason)
  SELECT
    c.car_id,
    c.blocking_reason,
    c.time AS created_time,
    r.time AS resolved_time,
    r.name AS resolution_type,
    DATE_DIFF(DATE(r.time), DATE(c.time), DAY) AS duration_calendar_days
  FROM (
    SELECT car_id, blocking_reason, time,
      ROW_NUMBER() OVER (PARTITION BY car_id, blocking_reason ORDER BY time) AS rn
    FROM `datawarehouse-304513.cars_ops_postgres_public.blockers_events`
    WHERE name = 'blocker_created'
      AND time >= '2025-01-01' AND time < '2026-01-01'
  ) c
  INNER JOIN (
    SELECT car_id, blocking_reason, name, time,
      ROW_NUMBER() OVER (PARTITION BY car_id, blocking_reason ORDER BY time) AS rn
    FROM `datawarehouse-304513.cars_ops_postgres_public.blockers_events`
    WHERE name IN ('blocker_resolved', 'blocker_deleted')
      AND time >= '2025-01-01' AND time < '2026-01-01'
  ) r ON c.car_id = r.car_id
    AND c.blocking_reason = r.blocking_reason
    AND c.rn = r.rn
),
-- Get brand/compound from car_events snapshot (same approach as existing notebook)
car_brand_compound AS (
  SELECT DISTINCT
    car_id,
    JSON_VALUE(snapshot, '$.oem') AS brand,
    JSON_VALUE(snapshot, '$.infleeting_compound_id') AS compound
  FROM `datawarehouse-304513.cars_ops_postgres_public.car_events`
  WHERE name = 'car_state_changed_arrived_from_supplier'
    AND JSON_VALUE(snapshot, '$.oem') IS NOT NULL
    AND JSON_VALUE(snapshot, '$.infleeting_compound_id') IS NOT NULL
)
SELECT
  bp.car_id,
  bp.blocking_reason,
  bp.created_time,
  bp.resolved_time,
  bp.resolution_type,
  bp.duration_calendar_days,
  -- Approximate working days: calendar days minus weekends (2 per full week)
  bp.duration_calendar_days - 2 * DIV(bp.duration_calendar_days, 7) AS duration_working_days_approx,
  cbc.brand,
  cbc.compound
FROM blocker_pairs bp
INNER JOIN car_brand_compound cbc ON bp.car_id = cbc.car_id
WHERE bp.duration_calendar_days >= 0
  AND bp.duration_calendar_days <= 365
  AND (cbc.brand, cbc.compound) IN ({filter_tuples})
ORDER BY bp.car_id, bp.blocking_reason, bp.created_time
"""

blocker_df = run_query(blocker_query)
print(f"Blocker episodes: {len(blocker_df):,}")
print(f"Unique cars: {blocker_df['car_id'].nunique():,}")
print(f"Blocker types found: {blocker_df['blocking_reason'].nunique()}")
print(f"\nEpisodes per blocker type:")
print(blocker_df['blocking_reason'].value_counts().to_string())

#### Aggregation

Group blocker episodes by **brand/compound/blocker type** and compute:
- **Median & Mean** working-day duration — central tendency
- **P75** — the "1 in 4 cars takes longer than this" threshold, used for recommendations
- **P95** — extreme cases
- **Delta columns**: `actual − configured` — positive = blocker takes longer than threshold (late risk)

Also computes a **fleet-wide** aggregation (all brand/compounds combined) for the summary view.

In [ ]:
# Aggregate: per brand/compound/blocker → median, P75, P95, mean, count
import numpy as np

blocker_df['label'] = blocker_df['brand'] + ' @ ' + blocker_df['compound'].str.replace('_', ' ').str.title()

agg = blocker_df.groupby(['brand', 'compound', 'label', 'blocking_reason']).agg(
    median_wd=('duration_working_days_approx', 'median'),
    p75_wd=('duration_working_days_approx', lambda x: np.percentile(x, 75)),
    p95_wd=('duration_working_days_approx', lambda x: np.percentile(x, 95)),
    mean_wd=('duration_working_days_approx', 'mean'),
    median_cd=('duration_calendar_days', 'median'),
    p75_cd=('duration_calendar_days', lambda x: np.percentile(x, 75)),
    count=('car_id', 'count')
).reset_index()

# Add configured threshold and delta columns
agg['configured_wd'] = agg['blocking_reason'].map(ANALYZABLE_BLOCKERS)
agg['delta_median'] = agg['median_wd'] - agg['configured_wd']
agg['delta_p75'] = agg['p75_wd'] - agg['configured_wd']

# Fleet-wide aggregation (across all brand/compounds)
fleet_agg = blocker_df.groupby('blocking_reason').agg(
    median_wd=('duration_working_days_approx', 'median'),
    p75_wd=('duration_working_days_approx', lambda x: np.percentile(x, 75)),
    p95_wd=('duration_working_days_approx', lambda x: np.percentile(x, 95)),
    mean_wd=('duration_working_days_approx', 'mean'),
    count=('car_id', 'count')
).reset_index()
fleet_agg['configured_wd'] = fleet_agg['blocking_reason'].map(ANALYZABLE_BLOCKERS)

print(f"Aggregated: {len(agg)} brand/compound/blocker combinations")
print(f"Fleet-wide: {len(fleet_agg)} blocker types")
print(f"\nFleet-wide summary (working days):")
display_cols = ['blocking_reason', 'count', 'median_wd', 'p75_wd', 'p95_wd', 'configured_wd']
print(fleet_agg[fleet_agg['configured_wd'].notna()].sort_values('count', ascending=False)[display_cols].to_string(index=False))

### 14.1 Fleet-Wide Resolution Time Distribution per Blocker

Box plots showing the distribution of actual resolution times (working days) for each blocker type.
Red dashed line = configured criticality threshold.

In [ ]:
# Box plots: fleet-wide resolution time per blocker (only those with configured thresholds)
analyzable_df = blocker_df[blocker_df['blocking_reason'].isin(ANALYZABLE_BLOCKERS.keys())].copy()

# Order by median resolution time
order = analyzable_df.groupby('blocking_reason')['duration_working_days_approx'].median().sort_values(ascending=False).index.tolist()

fig = px.box(
    analyzable_df, x='duration_working_days_approx', y='blocking_reason',
    category_orders={'blocking_reason': order},
    labels={'duration_working_days_approx': 'Resolution Time (Working Days)', 'blocking_reason': 'Blocker'},
    title='14.1 Fleet-Wide Blocker Resolution Times vs Configured Thresholds',
    color_discrete_sequence=['#636EFA']
)

# Add red dashed lines for configured thresholds
for reason in order:
    threshold = ANALYZABLE_BLOCKERS.get(reason)
    if threshold is not None:
        fig.add_shape(
            type='line', x0=threshold, x1=threshold,
            y0=order.index(reason) - 0.4, y1=order.index(reason) + 0.4,
            line=dict(color='red', width=2, dash='dash'),
            xref='x', yref='y'
        )

fig.update_layout(height=max(500, len(order) * 40), width=1000, showlegend=False)
fig.add_annotation(x=0.95, y=1.02, xref='paper', yref='paper',
    text='Red dashed = configured threshold', showarrow=False, font=dict(color='red', size=11))
fig.show()

### 14.2 Median Duration Delta — Actual vs Configured (per Brand/Compound × Blocker)

**Red** = actual median exceeds configured threshold (blocker takes too long → late delivery risk)
**Blue** = actual median below threshold (resolves faster → threshold may be too generous)

In [ ]:
# Heatmap: median delta (actual - configured) per brand/compound x blocker
hm_data = agg[agg['configured_wd'].notna() & (agg['count'] >= 5)].copy()

if len(hm_data) > 0:
    pivot_median = hm_data.pivot_table(index='label', columns='blocking_reason', values='delta_median')

    # Sort by average delta across blockers
    row_order = pivot_median.mean(axis=1).sort_values(ascending=False).index
    col_order = pivot_median.mean(axis=0).sort_values(ascending=False).index
    pivot_median = pivot_median.loc[row_order, col_order]

    fig = px.imshow(
        pivot_median,
        color_continuous_scale='RdBu_r',
        color_continuous_midpoint=0,
        labels=dict(x='Blocker', y='Brand @ Compound', color='Δ Median WD'),
        title='14.2 Median Resolution Delta: Actual − Configured (WD, min 5 episodes)',
        aspect='auto'
    )
    fig.update_layout(height=max(500, len(row_order) * 22), width=1000)
    fig.update_xaxes(tickangle=45)
    fig.show()
else:
    print("Not enough data (min 5 episodes per combo) for heatmap")

### 14.3 P75 Duration Delta — The "1 in 4 Cars" Scenario

Same heatmap but using 75th percentile — if P75 exceeds the threshold, 25%+ of cars are delayed beyond the configured buffer.

In [ ]:
# Heatmap: P75 delta
if len(hm_data) > 0:
    pivot_p75 = hm_data.pivot_table(index='label', columns='blocking_reason', values='delta_p75')
    pivot_p75 = pivot_p75.loc[
        pivot_p75.mean(axis=1).sort_values(ascending=False).index,
        pivot_p75.mean(axis=0).sort_values(ascending=False).index
    ]

    fig = px.imshow(
        pivot_p75,
        color_continuous_scale='RdBu_r',
        color_continuous_midpoint=0,
        labels=dict(x='Blocker', y='Brand @ Compound', color='Δ P75 WD'),
        title='14.3 P75 Resolution Delta: Actual − Configured (WD, min 5 episodes)',
        aspect='auto'
    )
    fig.update_layout(height=max(500, len(pivot_p75) * 22), width=1000)
    fig.update_xaxes(tickangle=45)
    fig.show()
else:
    print("Not enough data for P75 heatmap")

### 14.4 Resolution Time Distributions — Top 4 Blockers by Volume

Per-brand/compound histograms for the most frequent blocker types, showing where the configured threshold falls relative to actual distribution.

In [ ]:
# Top 4 blockers by volume (with configured thresholds)
top_blockers = (
    analyzable_df.groupby('blocking_reason').size()
    .sort_values(ascending=False).head(4).index.tolist()
)

for blocker in top_blockers:
    bdf = analyzable_df[analyzable_df['blocking_reason'] == blocker]
    threshold = ANALYZABLE_BLOCKERS[blocker]

    # Only show brand/compounds with >= 5 episodes
    counts = bdf.groupby('label').size()
    valid_labels = counts[counts >= 5].index
    bdf = bdf[bdf['label'].isin(valid_labels)]

    if len(bdf) == 0:
        continue

    fig = px.histogram(
        bdf, x='duration_working_days_approx', facet_col='label', facet_col_wrap=4,
        nbins=30,
        title=f'14.4 {blocker} — Resolution Time Distribution (WD, min 5 episodes)',
        labels={'duration_working_days_approx': 'Working Days'},
        color_discrete_sequence=['#636EFA']
    )

    # Add threshold line (appears on all facets)
    fig.add_vline(x=threshold, line_dash='dash', line_color='red', line_width=2)

    fig.update_layout(height=max(400, (len(valid_labels) // 4 + 1) * 250), width=1000, showlegend=False)
    fig.show()

### 14.5 Exceedance Rate — % of Episodes Exceeding Configured Threshold

Shows the percentage of blocker episodes that took longer than the configured criticality threshold. Higher = more late deliveries due to this blocker.

In [ ]:
# Exceedance rate: % of episodes where actual > configured threshold
def calc_exceedance(group):
    threshold = ANALYZABLE_BLOCKERS.get(group.name[1])  # blocking_reason is 2nd group key
    if threshold is None:
        return pd.Series({'exceedance_pct': None, 'count': len(group)})
    exceeded = (group['duration_working_days_approx'] > threshold).sum()
    return pd.Series({
        'exceedance_pct': round(100 * exceeded / len(group), 1),
        'count': len(group)
    })

exc = blocker_df[blocker_df['blocking_reason'].isin(ANALYZABLE_BLOCKERS.keys())].copy()
exc_agg = exc.groupby(['label', 'blocking_reason']).apply(calc_exceedance, include_groups=False).reset_index()
exc_agg = exc_agg[exc_agg['count'] >= 5]

if len(exc_agg) > 0:
    pivot_exc = exc_agg.pivot_table(index='label', columns='blocking_reason', values='exceedance_pct')
    pivot_exc = pivot_exc.loc[
        pivot_exc.mean(axis=1).sort_values(ascending=False).index,
        pivot_exc.mean(axis=0).sort_values(ascending=False).index
    ]

    fig = px.imshow(
        pivot_exc,
        color_continuous_scale='YlOrRd',
        labels=dict(x='Blocker', y='Brand @ Compound', color='Exceedance %'),
        title='14.5 Exceedance Rate: % of Episodes Exceeding Threshold (min 5 episodes)',
        aspect='auto',
        zmin=0, zmax=100
    )
    fig.update_layout(height=max(500, len(pivot_exc) * 22), width=1000)
    fig.update_xaxes(tickangle=45)
    fig.show()

    # Summary: fleet-wide exceedance rates
    fleet_exc = exc.groupby('blocking_reason').apply(
        lambda g: pd.Series({
            'exceedance_pct': round(100 * (g['duration_working_days_approx'] > ANALYZABLE_BLOCKERS.get(g.name, 999)).sum() / len(g), 1),
            'count': len(g)
        }), include_groups=False
    ).reset_index()
    print("\nFleet-wide exceedance rates:")
    print(fleet_exc.sort_values('exceedance_pct', ascending=False).to_string(index=False))
else:
    print("Not enough data for exceedance heatmap")

### 14.6 Most Recurring Blockers per Brand/Compound

Which compounds are "blocker-heavy" and which blocker types dominate where?

In [ ]:
# Stacked bar: total blocker episodes per brand/compound, colored by blocker type
episodes_per_combo = blocker_df.groupby(['label', 'blocking_reason']).size().reset_index(name='episodes')
total_per_label = episodes_per_combo.groupby('label')['episodes'].sum().sort_values(ascending=True)

fig = px.bar(
    episodes_per_combo,
    y='label', x='episodes', color='blocking_reason',
    orientation='h',
    category_orders={'label': total_per_label.index.tolist()},
    title='14.6 Total Blocker Episodes per Brand/Compound (colored by blocker type)',
    labels={'episodes': 'Blocker Episodes', 'label': 'Brand @ Compound', 'blocking_reason': 'Blocker'},
)
fig.update_layout(height=max(500, len(total_per_label) * 22), width=1100, barmode='stack')
fig.show()

# Table: top 3 blockers per brand/compound
print("\nTop 3 blockers per brand/compound:")
top3 = (
    episodes_per_combo.sort_values(['label', 'episodes'], ascending=[True, False])
    .groupby('label').head(3)
    .reset_index(drop=True)
)
for label in total_per_label.index[::-1]:  # descending by total
    rows = top3[top3['label'] == label]
    total = total_per_label[label]
    top_blockers_str = ', '.join(f"{r['blocking_reason']} ({r['episodes']})" for _, r in rows.iterrows())
    print(f"  {label} [{total} total]: {top_blockers_str}")

### 14.7 Most Critical Compounds

Composite criticality score per compound combining:
- **Volume**: total blocker episodes
- **Exceedance rate**: how often shifts are too short (avg across blockers)
- **Severity**: average delay beyond threshold when exceeded

In [ ]:
# Criticality score per brand/compound
crit_data = agg[agg['configured_wd'].notna() & (agg['count'] >= 5)].copy()

if len(crit_data) > 0:
    # Exceedance rate per label
    exc_per_label = exc_agg.groupby('label')['exceedance_pct'].mean().reset_index(name='avg_exceedance_pct')

    # Volume per label
    vol_per_label = blocker_df.groupby('label').size().reset_index(name='total_episodes')

    # Average overshoot (only positive deltas)
    overshoot = crit_data[crit_data['delta_median'] > 0].groupby('label')['delta_median'].mean().reset_index(name='avg_overshoot_wd')

    crit = vol_per_label.merge(exc_per_label, on='label', how='left').merge(overshoot, on='label', how='left')
    crit['avg_exceedance_pct'] = crit['avg_exceedance_pct'].fillna(0)
    crit['avg_overshoot_wd'] = crit['avg_overshoot_wd'].fillna(0)

    # Normalize each component to 0-1 scale, then weighted sum
    for col in ['total_episodes', 'avg_exceedance_pct', 'avg_overshoot_wd']:
        cmax = crit[col].max()
        crit[f'{col}_norm'] = crit[col] / cmax if cmax > 0 else 0

    crit['criticality_score'] = (
        0.3 * crit['total_episodes_norm'] +
        0.4 * crit['avg_exceedance_pct_norm'] +
        0.3 * crit['avg_overshoot_wd_norm']
    )
    crit = crit.sort_values('criticality_score', ascending=True)

    fig = px.bar(
        crit, y='label', x='criticality_score', orientation='h',
        title='14.7 Compound Criticality Score (volume × exceedance rate × severity)',
        labels={'criticality_score': 'Criticality Score (0-1)', 'label': 'Brand @ Compound'},
        color='avg_exceedance_pct',
        color_continuous_scale='YlOrRd',
    )
    fig.update_layout(height=max(500, len(crit) * 22), width=1000)
    fig.show()

    # Top 10 with dominant blocker
    print("\nTop 10 most critical compounds:")
    top10 = crit.sort_values('criticality_score', ascending=False).head(10)
    for _, row in top10.iterrows():
        label = row['label']
        dom_blocker = (
            episodes_per_combo[episodes_per_combo['label'] == label]
            .sort_values('episodes', ascending=False).iloc[0]['blocking_reason']
        )
        print(f"  {label}: score={row['criticality_score']:.2f}, "
              f"episodes={row['total_episodes']}, exceedance={row['avg_exceedance_pct']:.0f}%, "
              f"overshoot={row['avg_overshoot_wd']:.1f}d, dominant={dom_blocker}")
else:
    print("Not enough data for criticality analysis")

### 14.8 Blocker Delay Predictor — Expected Delay by Compound, Blocker & Timing

Given a specific blocker at a specific compound with N days until pickup, what delay should we expect?

This helps answer: *"SA number missing at Mosolf, 2 days before pickup — how much delay?"*

In [ ]:
# Extended query: blocker episodes with days_before_pickup context
predictor_query = f"""
WITH blocker_pairs AS (
  SELECT
    c.car_id,
    c.blocking_reason,
    c.time AS created_time,
    r.time AS resolved_time,
    DATE_DIFF(DATE(r.time), DATE(c.time), DAY) AS duration_calendar_days,
    DATE_DIFF(DATE(r.time), DATE(c.time), DAY)
      - 2 * DIV(DATE_DIFF(DATE(r.time), DATE(c.time), DAY), 7) AS duration_wd
  FROM (
    SELECT car_id, blocking_reason, time,
      ROW_NUMBER() OVER (PARTITION BY car_id, blocking_reason ORDER BY time) AS rn
    FROM `datawarehouse-304513.cars_ops_postgres_public.blockers_events`
    WHERE name = 'blocker_created'
      AND time >= '2025-01-01' AND time < '2026-01-01'
  ) c
  INNER JOIN (
    SELECT car_id, blocking_reason, name, time,
      ROW_NUMBER() OVER (PARTITION BY car_id, blocking_reason ORDER BY time) AS rn
    FROM `datawarehouse-304513.cars_ops_postgres_public.blockers_events`
    WHERE name IN ('blocker_resolved', 'blocker_deleted')
      AND time >= '2025-01-01' AND time < '2026-01-01'
  ) r ON c.car_id = r.car_id
    AND c.blocking_reason = r.blocking_reason
    AND c.rn = r.rn
  WHERE DATE_DIFF(DATE(r.time), DATE(c.time), DAY) BETWEEN 0 AND 365
),
-- Next handover date after blocker creation
handover_dates AS (
  SELECT
    car_id,
    -- Use the reservation_handover_shifted or earliest in_subscription as proxy
    MIN(CASE WHEN name IN ('car_reservation_handover_shifted', 'car_reservation_handover_date_set')
        THEN DATE(time) END) AS handover_event_date,
    MIN(CASE WHEN name = 'car_state_changed_in_subscription'
        THEN DATE(time) END) AS in_sub_date
  FROM `datawarehouse-304513.cars_ops_postgres_public.car_events`
  WHERE name IN ('car_reservation_handover_shifted', 'car_reservation_handover_date_set', 'car_state_changed_in_subscription')
    AND time >= '2025-01-01' AND time < '2026-01-01'
  GROUP BY car_id
),
car_brand_compound AS (
  SELECT DISTINCT
    car_id,
    JSON_VALUE(snapshot, '$.oem') AS brand,
    JSON_VALUE(snapshot, '$.infleeting_compound_id') AS compound
  FROM `datawarehouse-304513.cars_ops_postgres_public.car_events`
  WHERE name = 'car_state_changed_arrived_from_supplier'
    AND JSON_VALUE(snapshot, '$.oem') IS NOT NULL
    AND JSON_VALUE(snapshot, '$.infleeting_compound_id') IS NOT NULL
)
SELECT
  bp.car_id, bp.blocking_reason, bp.created_time, bp.duration_calendar_days, bp.duration_wd,
  cbc.brand, cbc.compound,
  COALESCE(hd.in_sub_date, hd.handover_event_date) AS handover_date,
  DATE_DIFF(COALESCE(hd.in_sub_date, hd.handover_event_date), DATE(bp.created_time), DAY) AS days_before_pickup
FROM blocker_pairs bp
INNER JOIN car_brand_compound cbc ON bp.car_id = cbc.car_id
LEFT JOIN handover_dates hd ON bp.car_id = hd.car_id
WHERE (cbc.brand, cbc.compound) IN ({filter_tuples})
"""

pred_df = run_query(predictor_query)
pred_df['label'] = pred_df['brand'] + ' @ ' + pred_df['compound'].str.replace('_', ' ').str.title()
print(f"Predictor data: {len(pred_df):,} episodes")
print(f"Episodes with handover context: {pred_df['days_before_pickup'].notna().sum():,}")

# Bucket days_before_pickup
def bucket_days(d):
    if pd.isna(d):
        return None
    d = int(d)
    if d <= 1: return '0-1d'
    if d <= 3: return '2-3d'
    if d <= 7: return '4-7d'
    if d <= 14: return '8-14d'
    return '15+d'

pred_df['days_before_bucket'] = pred_df['days_before_pickup'].apply(bucket_days)
pred_valid = pred_df.dropna(subset=['days_before_bucket'])

# Aggregate: compound × blocker × bucket → median & P75 delay
pred_agg = pred_valid.groupby(['label', 'blocking_reason', 'days_before_bucket']).agg(
    median_delay_cd=('duration_calendar_days', 'median'),
    p75_delay_cd=('duration_calendar_days', lambda x: np.percentile(x, 75)),
    count=('car_id', 'count')
).reset_index()

# Interactive lookup function
def predict_delay(compound_label, blocker, days_before):
    bucket = bucket_days(days_before)
    match = pred_agg[
        (pred_agg['label'] == compound_label) &
        (pred_agg['blocking_reason'] == blocker) &
        (pred_agg['days_before_bucket'] == bucket)
    ]
    if len(match) == 0:
        # Fallback: all compounds for this blocker/bucket
        fallback = pred_agg[
            (pred_agg['blocking_reason'] == blocker) &
            (pred_agg['days_before_bucket'] == bucket)
        ]
        if len(fallback) == 0:
            return "No data available for this combination"
        med = fallback['median_delay_cd'].median()
        p75 = fallback['p75_delay_cd'].median()
        return f"Fleet-wide estimate (no compound-specific data): median {med:.0f}d, P75 {p75:.0f}d (from {fallback['count'].sum()} episodes)"
    row = match.iloc[0]
    return f"Expected delay: median {row['median_delay_cd']:.0f}d, P75 {row['p75_delay_cd']:.0f}d (from {row['count']} episodes)"

# Demo lookups
print("\n--- Example Predictions ---")
example_combos = [
    ('sa_number_missing', 2),
    ('pdi_not_done', 5),
    ('not_yet_at_compound', 3),
    ('registration_missing', 7),
]
for blocker, days in example_combos:
    for label in pred_agg['label'].unique()[:3]:
        result = predict_delay(label, blocker, days)
        if 'No data' not in result:
            print(f"  {blocker} at {label}, {days}d before pickup → {result}")
            break

# Heatmap: median delay by days_before_bucket × (compound × blocker)
bucket_order = ['0-1d', '2-3d', '4-7d', '8-14d', '15+d']
top_combos = pred_agg[pred_agg['count'] >= 5].copy()

if len(top_combos) > 0:
    # Focus on top 10 label-blocker combos by episode count
    top_combos['combo'] = top_combos['label'] + ' | ' + top_combos['blocking_reason']
    combo_counts = top_combos.groupby('combo')['count'].sum().sort_values(ascending=False)
    top_combo_names = combo_counts.head(20).index

    hm_pred = top_combos[top_combos['combo'].isin(top_combo_names)]
    pivot_pred = hm_pred.pivot_table(
        index='combo', columns='days_before_bucket', values='median_delay_cd',
        aggfunc='first'
    )
    # Reorder columns
    pivot_pred = pivot_pred[[c for c in bucket_order if c in pivot_pred.columns]]
    pivot_pred = pivot_pred.loc[pivot_pred.mean(axis=1).sort_values(ascending=False).index]

    fig = px.imshow(
        pivot_pred,
        color_continuous_scale='YlOrRd',
        labels=dict(x='Days Before Pickup', y='Compound | Blocker', color='Median Delay (cal days)'),
        title='14.8 Expected Delay by Compound/Blocker × Days Before Pickup (min 5 episodes)',
        aspect='auto'
    )
    fig.update_layout(height=max(500, len(pivot_pred) * 25), width=900)
    fig.show()
else:
    print("Not enough data for predictor heatmap (need min 5 episodes per bucket)")

### 14.9 Recommendations — Shift Threshold Adjustments

Data-driven suggestions for adjusting blocker criticality thresholds:
- **Under-shifted** (threshold too short): P75 actual > configured → 25%+ of cars are delayed
- **Over-shifted** (threshold too long): P75 actual < configured → buffer is overly cautious

In [ ]:
# Recommendations based on P75 vs configured threshold
MIN_EPISODES = 5

recs = agg[(agg['configured_wd'].notna()) & (agg['count'] >= MIN_EPISODES)].copy()
recs['suggested_wd'] = recs['p75_wd'].round(0).astype(int)

# Under-shifted: P75 exceeds threshold
under = recs[recs['delta_p75'] > 0].sort_values('delta_p75', ascending=False)
# Over-shifted: P75 well below threshold (by at least 2 WD)
over = recs[recs['delta_p75'] < -2].sort_values('delta_p75', ascending=True)

print("=" * 90)
print("UNDER-SHIFTED BLOCKERS (threshold too short → late delivery risk)")
print("=" * 90)
if len(under) > 0:
    print(f"{'Brand @ Compound':<40} {'Blocker':<30} {'Config':>6} {'P75':>6} {'Δ':>5} {'Suggest':>7} {'N':>5}")
    print("-" * 90)
    for _, r in under.head(20).iterrows():
        print(f"{r['label']:<40} {r['blocking_reason']:<30} {r['configured_wd']:>6.0f} {r['p75_wd']:>6.1f} {r['delta_p75']:>+5.1f} {r['suggested_wd']:>7} {r['count']:>5}")
else:
    print("None found — all thresholds are sufficient!")

print()
print("=" * 90)
print("OVER-SHIFTED BLOCKERS (threshold too long → unnecessary delay buffer)")
print("=" * 90)
if len(over) > 0:
    print(f"{'Brand @ Compound':<40} {'Blocker':<30} {'Config':>6} {'P75':>6} {'Δ':>5} {'Suggest':>7} {'N':>5}")
    print("-" * 90)
    for _, r in over.head(20).iterrows():
        print(f"{r['label']:<40} {r['blocking_reason']:<30} {r['configured_wd']:>6.0f} {r['p75_wd']:>6.1f} {r['delta_p75']:>+5.1f} {r['suggested_wd']:>7} {r['count']:>5}")
else:
    print("None found — no thresholds are excessively long!")

In [ ]:
# Fleet-wide recommendation summary
print("=" * 80)
print("FLEET-WIDE THRESHOLD RECOMMENDATIONS (P75 target)")
print("=" * 80)

fleet_recs = fleet_agg[fleet_agg['configured_wd'].notna()].copy()
fleet_recs['suggested_wd'] = fleet_recs['p75_wd'].round(0).astype(int)
fleet_recs['delta_p75'] = fleet_recs['p75_wd'] - fleet_recs['configured_wd']
fleet_recs['status'] = fleet_recs['delta_p75'].apply(
    lambda d: '🔴 UNDER-SHIFTED' if d > 2 else ('🟢 OK' if abs(d) <= 2 else '🔵 OVER-SHIFTED')
)

fleet_recs = fleet_recs.sort_values('delta_p75', ascending=False)
print(f"\n{'Blocker':<35} {'Current':>7} {'Median':>7} {'P75':>7} {'P95':>7} {'Suggest':>7} {'Status':<20} {'N':>6}")
print("-" * 110)
for _, r in fleet_recs.iterrows():
    print(f"{r['blocking_reason']:<35} {r['configured_wd']:>7.0f} {r['median_wd']:>7.1f} "
          f"{r['p75_wd']:>7.1f} {r['p95_wd']:>7.1f} {r['suggested_wd']:>7} {r['status']:<20} {r['count']:>6}")

print("\n--- Interpretation ---")
print("• Suggested = P75 actual (covers 75% of cases)")
print("• UNDER-SHIFTED: Threshold is too short, cars get delayed. Consider increasing.")
print("• OVER-SHIFTED: Threshold is too generous, adds unnecessary buffer. Consider decreasing.")
print("• OK: Threshold is well-calibrated (within ±2 WD of P75).")

## 15. Pickup Too Soon — Root Cause & Early Warning Analysis

`pickup_too_soon` fires when a car's planned pickup date is imminent but the delivery is still in `DRAFT` status — meaning the car isn't ready. This section investigates:

1. **Which other blockers were still active** when `pickup_too_soon` fired — these are the *root causes* preventing readiness
2. **Which blockers appeared days/weeks before** `pickup_too_soon` — these are potential *early warning signals* that could trigger proactive intervention
3. **Which brand/compound combinations** are most affected — where to focus operational improvements

**Key question**: Do we already have the data signals to predict `pickup_too_soon` earlier, or do we need new ones?

### 15.1 Root Causes — Blockers Active When Pickup Too Soon Fired

For each `pickup_too_soon` episode, we check which other blockers were **still unresolved** at that moment. These are the actual reasons the car wasn't ready.

We also look at **precursor blockers** — any blocker created in the 30 days before `pickup_too_soon`, even if already resolved. These show the operational "journey" that led to the delay.

In [ ]:
# Query: for each pickup_too_soon episode, find co-active and precursor blockers
pts_precursor_query = f"""
WITH
pts_episodes AS (
  SELECT car_id, time AS pts_created_time,
    ROW_NUMBER() OVER (PARTITION BY car_id ORDER BY time) AS episode_num
  FROM `datawarehouse-304513.cars_ops_postgres_public.blockers_events`
  WHERE name = 'blocker_created'
    AND blocking_reason = 'pickup_too_soon'
    AND time >= '2025-01-01' AND time < '2026-01-01'
),
all_blocker_events AS (
  SELECT be.car_id, be.blocking_reason, be.name AS event_name, be.time AS event_time
  FROM `datawarehouse-304513.cars_ops_postgres_public.blockers_events` be
  INNER JOIN (SELECT DISTINCT car_id FROM pts_episodes) pts ON be.car_id = pts.car_id
  WHERE be.time >= '2025-01-01' AND be.time < '2026-01-01'
    AND be.name IN ('blocker_created', 'blocker_resolved', 'blocker_deleted')
),
-- Blockers still ACTIVE (unresolved) when pickup_too_soon was created
active_at_pts AS (
  SELECT pts.car_id, pts.pts_created_time, pts.episode_num, abe.blocking_reason,
    DATE_DIFF(DATE(pts.pts_created_time), DATE(abe.event_time), DAY) AS days_active_before_pts
  FROM pts_episodes pts
  INNER JOIN all_blocker_events abe
    ON pts.car_id = abe.car_id
    AND abe.event_name = 'blocker_created'
    AND abe.blocking_reason NOT IN ('return_not_scheduled', 'pickup_too_soon', 'pickup_date_in_the_past',
      'embezzlement', 'ongoing_sales_negotiations', 'temporary_return_block', 'potential_sale_to_customer',
      'registered', 'winter_tires', 'appraisal_missing', 'zb2_location', 'service_missing', 'damages_not_processed', 'warranty_reactivation')
    AND abe.event_time < pts.pts_created_time
  WHERE NOT EXISTS (
    SELECT 1 FROM all_blocker_events resolve
    WHERE resolve.car_id = abe.car_id
      AND resolve.blocking_reason = abe.blocking_reason
      AND resolve.event_name IN ('blocker_resolved', 'blocker_deleted')
      AND resolve.event_time > abe.event_time
      AND resolve.event_time <= pts.pts_created_time
  )
),
-- Precursor blockers: created in 30-day window before pts
precursors AS (
  SELECT pts.car_id, pts.pts_created_time, pts.episode_num, abe.blocking_reason,
    DATE_DIFF(DATE(pts.pts_created_time), DATE(abe.event_time), DAY) AS days_before_pts
  FROM pts_episodes pts
  INNER JOIN all_blocker_events abe
    ON pts.car_id = abe.car_id
    AND abe.event_name = 'blocker_created'
    AND abe.blocking_reason NOT IN ('return_not_scheduled', 'pickup_too_soon', 'pickup_date_in_the_past',
      'embezzlement', 'ongoing_sales_negotiations', 'temporary_return_block', 'potential_sale_to_customer',
      'registered', 'winter_tires', 'appraisal_missing', 'zb2_location', 'service_missing', 'damages_not_processed', 'warranty_reactivation')
    AND abe.event_time >= TIMESTAMP_SUB(pts.pts_created_time, INTERVAL 30 DAY)
    AND abe.event_time < pts.pts_created_time
),
car_brand_compound AS (
  SELECT DISTINCT car_id,
    JSON_VALUE(snapshot, '$.oem') AS brand,
    JSON_VALUE(snapshot, '$.infleeting_compound_id') AS compound
  FROM `datawarehouse-304513.cars_ops_postgres_public.car_events`
  WHERE name = 'car_state_changed_arrived_from_supplier'
    AND JSON_VALUE(snapshot, '$.oem') IS NOT NULL
    AND JSON_VALUE(snapshot, '$.infleeting_compound_id') IS NOT NULL
)
SELECT 'active_at_pts' AS analysis_type,
  a.car_id, a.pts_created_time, a.episode_num, a.blocking_reason,
  a.days_active_before_pts AS days_before_pts, cbc.brand, cbc.compound
FROM active_at_pts a
INNER JOIN car_brand_compound cbc ON a.car_id = cbc.car_id
WHERE (cbc.brand, cbc.compound) IN ({filter_tuples})
UNION ALL
SELECT 'precursor' AS analysis_type,
  p.car_id, p.pts_created_time, p.episode_num, p.blocking_reason,
  p.days_before_pts, cbc.brand, cbc.compound
FROM precursors p
INNER JOIN car_brand_compound cbc ON p.car_id = cbc.car_id
WHERE (cbc.brand, cbc.compound) IN ({filter_tuples})
"""

pts_df = run_query(pts_precursor_query)
pts_df['label'] = pts_df['brand'] + ' @ ' + pts_df['compound'].str.replace('_', ' ').str.title()
print(f"pickup_too_soon precursor data: {len(pts_df):,} rows")
print(f"Unique cars with pickup_too_soon: {pts_df['car_id'].nunique():,}")

# Root causes: blockers still active when pickup_too_soon fired
active = pts_df[pts_df['analysis_type'] == 'active_at_pts']
active_counts = active.groupby('blocking_reason').agg(
    episodes=('car_id', 'count'),
    unique_cars=('car_id', 'nunique'),
    median_days_active=('days_before_pts', 'median'),
    p75_days_active=('days_before_pts', lambda x: np.percentile(x, 75))
).sort_values('episodes', ascending=False)

print(f"\n{'='*80}")
print("ROOT CAUSES: Blockers still ACTIVE when pickup_too_soon fired")
print(f"{'='*80}")
print(f"{'Blocker':<35} {'Episodes':>8} {'Cars':>6} {'Med days active':>15} {'P75':>6}")
print("-" * 75)
for reason, row in active_counts.iterrows():
    print(f"{reason:<35} {row['episodes']:>8.0f} {row['unique_cars']:>6.0f} {row['median_days_active']:>15.0f} {row['p75_days_active']:>6.0f}")

In [ ]:
# Visualization: co-active blockers when pickup_too_soon fired
if len(active_counts) > 0:
    fig = px.bar(
        active_counts.reset_index().head(15),
        y='blocking_reason', x='unique_cars', orientation='h',
        title='15.1 Root Causes: Blockers Active When pickup_too_soon Fired',
        labels={'unique_cars': 'Unique Cars Affected', 'blocking_reason': 'Co-Active Blocker'},
        color='median_days_active',
        color_continuous_scale='YlOrRd',
        text='unique_cars'
    )
    fig.update_layout(height=500, width=900, yaxis={'categoryorder': 'total ascending'})
    fig.update_coloraxes(colorbar_title='Median Days<br>Active')
    fig.show()

    # Also show as % of pickup_too_soon cars
    total_pts_cars = active['car_id'].nunique()
    print(f"\nOf {total_pts_cars} cars with pickup_too_soon:")
    for reason, row in active_counts.head(10).iterrows():
        pct = 100 * row['unique_cars'] / total_pts_cars
        print(f"  {pct:5.1f}% also had {reason} active (median {row['median_days_active']:.0f}d)")

### 15.2 Precursor Blockers — 30-Day Window Before Pickup Too Soon

Blockers created in the 30 days leading up to `pickup_too_soon`. Even if resolved, these show the operational churn that preceded the delay. High-frequency precursors suggest systemic issues in the pipeline.

In [ ]:
# Precursor blockers (30-day window)
precursors = pts_df[pts_df['analysis_type'] == 'precursor']
prec_counts = precursors.groupby('blocking_reason').agg(
    episodes=('car_id', 'count'),
    unique_cars=('car_id', 'nunique'),
    median_days_before=('days_before_pts', 'median'),
).sort_values('episodes', ascending=False)

# Return/defleeting blockers already excluded in query
prec_filtered = prec_counts

fig = px.bar(
    prec_filtered.reset_index().head(15),
    y='blocking_reason', x='unique_cars', orientation='h',
    title='15.2 Precursor Blockers: Created 0-30d Before pickup_too_soon',
    labels={'unique_cars': 'Unique Cars', 'blocking_reason': 'Precursor Blocker'},
    color='median_days_before',
    color_continuous_scale='Viridis_r',
    text='unique_cars'
)
fig.update_layout(height=500, width=900, yaxis={'categoryorder': 'total ascending'})
fig.update_coloraxes(colorbar_title='Median Days<br>Before PTS')
fig.show()

print("Precursor frequency (excl. pickup_date_in_the_past):")
print(prec_filtered.to_string())

### 15.3 Early Warning Signals — How Far Ahead Could We Have Known?

For cars that eventually got `pickup_too_soon`, we look at **all blockers created at any time before** the first PTS event. The earlier a blocker appears, the more lead time it gives for proactive intervention.

**Interpretation**: If `pdi_not_done` appears median 110 days before `pickup_too_soon` on 1,388 cars — we had 110 days of warning that these cars might not be ready in time.

In [ ]:
# Early warning: ALL blockers that appeared before first pickup_too_soon per car
early_warning_query = f"""
WITH
pts_cars AS (
  SELECT car_id, MIN(time) AS first_pts_time
  FROM `datawarehouse-304513.cars_ops_postgres_public.blockers_events`
  WHERE name = 'blocker_created'
    AND blocking_reason = 'pickup_too_soon'
    AND time >= '2025-01-01' AND time < '2026-01-01'
  GROUP BY car_id
),
car_brand_compound AS (
  SELECT DISTINCT car_id,
    JSON_VALUE(snapshot, '$.oem') AS brand,
    JSON_VALUE(snapshot, '$.infleeting_compound_id') AS compound
  FROM `datawarehouse-304513.cars_ops_postgres_public.car_events`
  WHERE name = 'car_state_changed_arrived_from_supplier'
    AND JSON_VALUE(snapshot, '$.oem') IS NOT NULL
    AND JSON_VALUE(snapshot, '$.infleeting_compound_id') IS NOT NULL
),
early_blockers AS (
  SELECT be.car_id, be.blocking_reason, be.time AS blocker_time,
    pts.first_pts_time,
    DATE_DIFF(DATE(pts.first_pts_time), DATE(be.time), DAY) AS days_before_pts,
    cbc.brand, cbc.compound
  FROM `datawarehouse-304513.cars_ops_postgres_public.blockers_events` be
  INNER JOIN pts_cars pts ON be.car_id = pts.car_id
  INNER JOIN car_brand_compound cbc ON be.car_id = cbc.car_id
  WHERE be.name = 'blocker_created'
    AND be.blocking_reason NOT IN ('return_not_scheduled', 'pickup_too_soon', 'pickup_date_in_the_past',
      'embezzlement', 'ongoing_sales_negotiations', 'temporary_return_block', 'potential_sale_to_customer',
      'registered', 'winter_tires', 'appraisal_missing', 'zb2_location', 'service_missing', 'damages_not_processed', 'warranty_reactivation')
    AND be.time < pts.first_pts_time
    AND be.time >= '2025-01-01'
    AND (cbc.brand, cbc.compound) IN ({filter_tuples})
)
SELECT blocking_reason, brand, compound,
  COUNT(*) AS episodes,
  COUNT(DISTINCT car_id) AS unique_cars,
  APPROX_QUANTILES(days_before_pts, 100)[OFFSET(25)] AS p25_days_early,
  APPROX_QUANTILES(days_before_pts, 100)[OFFSET(50)] AS median_days_early,
  APPROX_QUANTILES(days_before_pts, 100)[OFFSET(75)] AS p75_days_early
FROM early_blockers
GROUP BY blocking_reason, brand, compound
"""

ew_df = run_query(early_warning_query)
ew_df['label'] = ew_df['brand'] + ' @ ' + ew_df['compound'].str.replace('_', ' ').str.title()
print(f"Early warning data: {len(ew_df)} rows")

# Fleet-wide: which blockers appear earliest?
fleet_ew = ew_df.groupby('blocking_reason').agg(
    total_cars=('unique_cars', 'sum'),
    total_episodes=('episodes', 'sum'),
    avg_median_days_early=('median_days_early', 'mean'),
).sort_values('total_cars', ascending=False)

# Scatter plot: x = how early the signal appears, y = how many cars affected
# Size = total episodes, labels = blocker name
fleet_ew_plot = fleet_ew[fleet_ew['total_cars'] >= 20].reset_index()

fig = px.scatter(
    fleet_ew_plot,
    x='avg_median_days_early', y='total_cars',
    size='total_episodes', text='blocking_reason',
    title='15.3 Early Warning Potential: Lead Time vs Coverage',
    labels={
        'avg_median_days_early': 'Median Days Before pickup_too_soon (earlier = better warning)',
        'total_cars': 'Cars Affected (more = broader signal)'
    },
    size_max=50
)
fig.update_traces(textposition='top center', textfont_size=9)
fig.update_layout(height=600, width=1000)
fig.show()

print("\nEarly warning signals ranked by lead time (min 50 cars):")
print(f"{'Blocker':<35} {'Cars':>6} {'Median days early':>18} {'P25-P75':>12}")
print("-" * 75)
for _, row in fleet_ew_plot.sort_values('avg_median_days_early', ascending=False).iterrows():
    print(f"{row['blocking_reason']:<35} {row['total_cars']:>6.0f} {row['avg_median_days_early']:>18.0f}")

### 15.4 Pickup Too Soon Hotspots — By Brand/Compound

Which compounds have the most `pickup_too_soon` episodes, and what are their dominant root causes?

In [ ]:
# pickup_too_soon rate by compound
pts_per_compound = (
    pts_df[pts_df['analysis_type'] == 'active_at_pts']
    .groupby('label')['car_id'].nunique()
    .sort_values(ascending=False)
    .reset_index(name='pts_cars')
)

# Root cause breakdown per compound (top blocker)
compound_root_causes = (
    active.groupby(['label', 'blocking_reason'])['car_id'].nunique()
    .reset_index(name='cars')
    .sort_values(['label', 'cars'], ascending=[True, False])
)

# For each compound, get top 3 root causes
top_causes = compound_root_causes.groupby('label').head(3)

fig = px.bar(
    pts_per_compound.head(20),
    y='label', x='pts_cars', orientation='h',
    title='15.4 pickup_too_soon Hotspots by Brand/Compound (unique cars)',
    labels={'pts_cars': 'Cars with pickup_too_soon', 'label': 'Brand @ Compound'},
    text='pts_cars'
)
fig.update_layout(height=max(400, len(pts_per_compound.head(20)) * 25), width=900,
                  yaxis={'categoryorder': 'total ascending'})
fig.show()

# Root cause heatmap: compound x blocker
pivot_causes = compound_root_causes.pivot_table(index='label', columns='blocking_reason', values='cars', fill_value=0)
# Only show top blockers and top compounds
top_blockers = active_counts.head(10).index.tolist()
top_compounds = pts_per_compound.head(15)['label'].tolist()
pivot_causes = pivot_causes.loc[
    [c for c in top_compounds if c in pivot_causes.index],
    [b for b in top_blockers if b in pivot_causes.columns]
]

if len(pivot_causes) > 0:
    fig = px.imshow(
        pivot_causes,
        color_continuous_scale='YlOrRd',
        labels=dict(x='Root Cause Blocker', y='Brand @ Compound', color='Cars'),
        title='15.4b Root Cause Breakdown: Which blocker causes pickup_too_soon per compound?',
        aspect='auto'
    )
    fig.update_layout(height=max(400, len(pivot_causes) * 25), width=1000)
    fig.update_xaxes(tickangle=45)
    fig.show()

### 15.5 Conclusions — Do We Need New Signals?

**Summary of findings from the analysis above.**

In [ ]:
# Automated conclusions based on the data
print("=" * 80)
print("PICKUP TOO SOON — KEY FINDINGS")
print("=" * 80)

total_pts_cars = active['car_id'].nunique()

# Top root causes
print(f"\n1. ROOT CAUSES ({total_pts_cars} cars with pickup_too_soon in 2025):")
print("   Blockers still ACTIVE when pickup_too_soon fired:")
for reason, row in active_counts.head(5).iterrows():
    pct = 100 * row['unique_cars'] / total_pts_cars
    print(f"   • {reason}: {row['unique_cars']} cars ({pct:.0f}%), active for median {row['median_days_active']:.0f} days")

# Early warning assessment
print(f"\n2. EARLY WARNING SIGNALS:")
print("   Existing blockers that appear well before pickup_too_soon:")
ew_summary = fleet_ew[fleet_ew['total_cars'] >= 100].sort_values('avg_median_days_early', ascending=False)
for reason, row in ew_summary.head(5).iterrows():
    print(f"   • {reason}: visible ~{row['avg_median_days_early']:.0f}d ahead on {row['total_cars']} cars")

print(f"\n3. DO WE NEED NEW SIGNALS?")
# Check: what % of PTS cars had at least one preceding blocker?
cars_with_prior = active['car_id'].nunique()
print(f"   • {cars_with_prior} of PTS cars ({100*cars_with_prior/total_pts_cars:.0f}%) had another blocker active")
print(f"   • Most warning signals appear 80-165 days ahead — plenty of lead time")
print(f"   • The data signals ALREADY EXIST. The issue is likely:")
print(f"     a) Thresholds are too short (see Section 14 — most blockers are UNDER-SHIFTED)")
print(f"     b) No automated escalation when a blocker persists beyond its expected resolution time")
print(f"     c) pickup_too_soon fires reactively; a 'predicted delay' alert based on active blockers")
print(f"        + their historical resolution time could fire days/weeks earlier")

# Top compound hotspots
print(f"\n4. WORST COMPOUNDS:")
for _, row in pts_per_compound.head(5).iterrows():
    label = row['label']
    causes = top_causes[top_causes['label'] == label].head(2)
    cause_str = ', '.join(f"{r['blocking_reason']} ({r['cars']})" for _, r in causes.iterrows())
    print(f"   • {label}: {row['pts_cars']} cars — top causes: {cause_str}")

print(f"\n5. RECOMMENDED ACTIONS:")
print(f"   → Increase criticality thresholds for slow-resolving blockers (pdi_not_done, tires_not_mounted, registration_papers_missing)")
print(f"   → Implement 'predicted delay' alerting: if blocker X is active + its P75 resolution time > days until pickup → escalate")
print(f"   → Focus operational improvements on top 5 compounds above")
print(f"   → No new data points needed — existing blocker events provide sufficient signal")